### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by MajRaven** [alRex-U/ParCool#100]
**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: 1.19.2-1.0.0.1-r
+ Forge Version (optional): 43.1.2

**Additional Data**
[crash-2022-08-28_20.42.30-fml.txt](https://github.com/alRex-U/ParCool/files/9440192/crash-2022-08-28_20.42.30-fml.txt)

**Comment by alRex-U** [comment]
Oh I have seen this error many times. Sorry I will apply a patch soon

**Comment by alRex-U** [comment]
Please re-open this if same error occurred
