### ISSUE TITLE
The javafx.util.pair class is unavailable in some java versions

### ISSUE THREAD

**Issue by MMVVMM** [alRex-U/ParCool#101]
**Summary**
The javafx.util.pair class is unavailable in some java versions.

**Running Environment**
+ Minecraft Version:1.16.5
+ ParCool Version:2.0.0.1-R
+ Forge Version (optional):36.2.39
+ Java Version: 1.8.0_332, Azul Systems, Inc.
+ Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.

**Detail**
When I tried to move in the world,a server-side crash occured.
"Caused by: java.lang.ClassNotFoundException: javafx.util.Pair"
See:https://github.com/alRex-U/ParCool/blob/1502fe61af799a4903c7332b128ba9d3e681f0e2/src/main/java/com/alrex/parcool/common/network/SyncActionStateMessage.java#L215
In some versions of openjdk, "jfxrt.jar" is missing for the uses of the javafx.util.pair class.
Can you please replace this using other methods?

**Additional Data**
Complete crash report:https://pastebin.com/Kw8VrY8K

**Comment by alRex-U** [comment]
Wow! Really I did not want to do but I used JavaFX module. It must be needs to fix soon.

~~too many classes named Pair annoying~~

**Comment by alRex-U** [comment]
Maybe I mistook javafx.util.Pair for javax.util.Pair (of course such class does not exist)
