### ISSUE TITLE
Strange Behaviors of Dodge and Breakfall

### ISSUE THREAD

**Issue by MMVVMM** [alRex-U/ParCool#103]
**Summary**
The first-person camera rotates imcorrectly when Dodge seems to be able to interrupt Breakfall.

**Running Environment**
+ Minecraft Version:1.16.5
+ ParCool Version:2.0.0.2-R

**Detail**
To reproduce it:
1.Make the keybinds of Dodge and Breakfall the same.
2.Hold the binded key.
While the camera rotates it suddenly interrupt at a vertical angel.

**Additional Data**

https://user-images.githubusercontent.com/81964663/189483796-f84daeaa-3284-4f75-9b40-c82c7fa8da43.mp4

**Comment by alRex-U** [comment]
Thank-you for reporting.

I will check it.
