### ISSUE TITLE
Invalid option

### ISSUE THREAD

**Issue by MMVVMM** [alRex-U/ParCool#105]
**Summary**
The invalid "Roll" option is not deleted although it was replaced by "Breakfall".
![image](https://user-images.githubusercontent.com/81964663/189485718-1dc0416c-b79c-423a-918e-e5d2f1700ea1.png)

**Running Environment**
+ Minecraft Version:1.16.5
+ ParCool Version:2.0.0.2-R

**Comment by alRex-U** [comment]
Thanks.
