### ISSUE TITLE
Can't slide if you disable crawl, and feature request

### ISSUE THREAD

**Issue by Jetpack-Cat** [alRex-U/ParCool#106]
Hey I wanted to add parcool to my modpack: https://www.curseforge.com/minecraft/modpacks/jetpack-cat

If I disable crawling, I can't use the slide feature. I really like the sliding feature but not crawling and would rather turn crawling off, but then I can't use the sliding feature.

**Running Environment**
+ Minecraft Version: 1.16.5
+ ParCool Version: ParCool-1.16.5-2.0.0.2-R.jar
+ Forge Version (optional):

**Detail**
I would like to disable crawling but keep the sliding feature. Also, when sliding, the player model flips around into a crawling pose at the end which looks pretty bad. I think sliding and crawling should be separate things, because the crawling animation doesn't look very good.

Also, would it be possible to add the amount for some of the features to the config? For example, how far you slide, how far you can wall run, etc?

Thanks!

**Comment by alRex-U** [comment]
Thanks for suggesting.

It sounds not so bad. I want to try it when i have time.
