### ISSUE TITLE
Wall bouncing is super unreliable

### ISSUE THREAD

**Issue by Jetpack-Cat** [alRex-U/ParCool#107]
1.16.5 Forge ParCool-1.16.5-2.0.0.2-R.jar

Wall bouncing is super unreliable, it's pretty hard to do realistically in an actual world. I turned off wall bouncing when facing a wall because it messes up elenai dodge's double jump. Maybe it should be easier to wall bounce, half the time I think i'm close enough to the wall as I jump at it sideways but i'm not and I just fall, making it something that's not really useful unless you can reliable use the feature.

Turning on wall bounce when facing wall really fixes the problem, but then if you have a double jump mod installed you will often times bounce off the wall when you're intending to double jump to get to higher ground.

I believe setting a delay for wall bouncing would fix the problem. So when you jump, you can't double jump for a configurable amount of ms. Maybe 100 ms delay before wall bouncing would work from the time you jump, that way you could still double jump near a wall without bouncing off.

**Comment by alRex-U** [comment]
As for setting a delay to double jump, double jump is not an action of ParCool so I cannot do it. Actually ParCool's Wall jump has already a delay of 250ms after going away from ground.
