### ISSUE TITLE
Allow repositioning of stamina HUD element through config

### ISSUE THREAD

**Issue by NoveritaDev** [alRex-U/ParCool#108]
Hello.

I'm working on creating a modpack, and unfortunately the stamina bar from this mod overlaps a HUD element from another (specifically the epic fight mod, though I doubt it matters).

Would it be reasonable to ask for an additional config option to specify a simple pixel offset to provide better compatibility with other mod HUDs?

Thanks for your time.

**Comment by NoveritaDev** [comment]
My mistake, another member of my team mentioned the issue and I did not take the time to read the config myself. Now I see that the options already exist. So... Thanks for reading my mind well ahead of time!

(I feel a bit dumb now, sorry about that.)

**Comment by alRex-U** [comment]
No problem. I hope these configs that are difficult to use would help you
