### ISSUE TITLE
book opening crash

### ISSUE THREAD

**Issue by thiccmeme** [alRex-U/ParCool#11]
[crash-2021-05-29_23.57.09-server.txt](https://github.com/alRex-U/ParCool/files/6565783/crash-2021-05-29_23.57.09-server.txt)

I'm not sure if the crash is an issue with parcool itself or another mod, however, I noticed I'm not the only one to experience a crash upon opening the guidebook.

**Comment by alRex-U** [comment]
Thank you for submitting crash reports again and again! I'll try to fix it.

**Comment by alRex-U** [comment]
The cause may be almost the same as the last time.  I'll fix it in the near future.
