### ISSUE TITLE
Stamina recovering command

### ISSUE THREAD

**Issue by LegoSuperNik** [alRex-U/ParCool#110]
Hey!
I was a big fan of SmartMoving which is not being updated now. But when I found your mod, I understand that it is better!

It would be nice if you add a command to recover stamina. I think it would be very useful for map makers.

**Comment by alRex-U** [comment]
Thanks for playing.

It may not bad. I was thinking of adding a potion for better stamina too. I will consider it.

**Comment by alRex-U** [comment]
this feature was added
