### ISSUE TITLE
[1.19.2] FOV judders with Block Runner

### ISSUE THREAD

**Issue by Baggytrousers27** [alRex-U/ParCool#111]
Forge 43.1.27
PuzzlesLib-v4.3.4-1.19.2-Forge
BlockRunner-v4.2.0-1.19.2-Forge
ParCool-1.19.2-1.0.0.2-R
Running on path blocks, assorted stone blocks etc. causes FOV to bug out.

![juddering](https://user-images.githubusercontent.com/15883796/192561559-30e50cee-3b5d-4519-96af-ecbe0e0df4a8.gif)

**Comment by alRex-U** [comment]
Thanks for reporting. I need to test it.

**Comment by oxoct** [comment]
The same problem occurred when using the Majrusz's Progressive Difficulty mod.
forge 43.1.16
Majrusz's Progressive Difficulty 1.5.11
ParCool-1.19.2-1.0.0.2-R

**Comment by alRex-U** [comment]
I had some tests with commands and CarryOn mod.
Then maybe adding the Slowness potion effect has the cause.

When this potion effect added, the speed-modifier of Fast-Run is removed for a moment. Soon ParCool re-apply this modifier to players. However, for example as for CarryOn mod, this apply slowdown effect which have 1tick lifetime every tick,
 so applying and removing occur every tick and the game looks like this bug shows

**Comment by alRex-U** [comment]
Ok the main cause is that ParCool apply speed modifier only in client-side.
Synchronization with server cause this

I can fix

**Comment by alRex-U** [comment]
I reopen this for supporting newer versions

**Comment by dhgameryt** [comment]
> I reopen this for supporting newer versions

i have the same issue, im using 1.19.2-1.0.0.2-R 
i have 200 mods so i dont know what causes it

https://user-images.githubusercontent.com/44879137/211387136-e5e05b54-f64f-4ce5-8a11-99206d6cff85.mp4

**Comment by ShadOhh** [comment]
This happens when speed is added, speed multiplier of any kind will result in this jitter. Even from potion i think

**Comment by ShadOhh** [comment]
wait no my bad not any speed just any additional speed that's outside of swiftness I think. I'm currently using a mod that adds shadow Cloak where you gain shadow form when you attack. Shadow form which is an effect grants speed and invis. This form brought stutters. So maybe any speed multiplier thats outside vanilla results in stutters.

**Comment by alRex-U** [comment]
It is already fixed and working on to porting it to newer versions please wait
