### ISSUE TITLE
Add modifier key for wall bouncing?

### ISSUE THREAD

**Issue by Jetpack-Cat** [alRex-U/ParCool#112]
1.16.5 forge newest parcool version
Could you add a key for wall bouncing so you have to hold the key down in order to wall bounce? I think that would fix wall bouncing interfering with double jumping. I'd like to leave wall bouncing while looking at a wall on, but i'm bouncing off so many walls unintentionally.

**Comment by alRex-U** [comment]
What you mean is to add a key for wall-jump and players have to continue to press it while they're in air? I wonder  when and how long time they press it.
What is that you think like?
