### ISSUE TITLE
[Suggestion] Make crawling let you go through 0.5 block spaces and add walking on-all-fours to make 1-block crawling look nicer

### ISSUE THREAD

**Issue by Catomax262** [alRex-U/ParCool#114]
**Summary**
Hitbox for crawling seems inaccurate, the body takes just 0.5 block spaces but is only allowed to go through 1 block space.

A thing would be for all-fours-walking to replace crawling, and pressing the all-fours key + shift would make the player crawl like usual.

What should all-fours-walking do? Nothing, just look nice. Maybe it could be an entire separate key to not break the sliding function.

**Comment by alRex-U** [comment]
Crawl action utilize vanilla swimming movement. So players cannot go through 0.5 block space.

As for the alternative action, please let me think. In fact, it may look strange but this is not so annoying players.
From a viewpoint of development, it need some works such as an animation and to test it is correctly synchronized with server(not impossible).
