### ISSUE TITLE
[Suggestion] Make wall-jumping easier

### ISSUE THREAD

**Issue by Catomax262** [alRex-U/ParCool#115]
**Summary**
For example make it so when you're doing a wall slide, your wall-jumps get a little more controllable.

**Comment by alRex-U** [comment]
What you mean by the word "more controllable? 
If you have some detailed idea, could you share them? Maybe I will implement it as default behavior, not only during wall-slide.
The controll should always be easier if possible.

**Comment by alRex-U** [comment]
Oh, it sounds good. Thank you for telling me.
