### ISSUE TITLE
[Suggestion] Make a Climbing Movement instead of GrabCliff in certain case.

### ISSUE THREAD

**Issue by COwOkies** [alRex-U/ParCool#119]
For exemple in this video :  (in a case where you have to climb up for a long time)
It's quiet annoying as you have to spam click the jump button
https://youtu.be/L_D2ni7xQOs

It would be better if there was a movement like this one in SmartMoving : 
https://www.minecraft-france.fr/wp-content/uploads/2014/10/bloggif_542fd0af21f46.gif

**Comment by alRex-U** [comment]
Hmm, as you said, it looks annoying. However I cannot soon come up with how to implement the behavior like the second video. Please let me think.

**Comment by COwOkies** [comment]
Good Luck with that !
