### ISSUE TITLE
add configurable keys for back flip, front flip, and fast running

### ISSUE THREAD

**Issue by thiccmeme** [alRex-U/ParCool#12]
I've gotten complaints from a few of my friends who use control as their sprint key that fast running overrides whatever key your sprinting is set to, as well as when double tapping w to sprint it is overridden by the front flip.

if there is anyway to make this not happen/not override the vanilla sprinting that would be great :)

**Comment by alRex-U** [comment]
Ok, I'll try it. Please tell them that I said thanks for this advice.

**Comment by alRex-U** [comment]
[Release](https://www.curseforge.com/minecraft/mc-mods/parcool/files/3330449)
