### ISSUE TITLE
[Suggestion] Add compatibility with Create's moving things

### ISSUE THREAD

**Issue by LegoSuperNik** [alRex-U/ParCool#120]
When you standing on moving platform that made with Create mod you can't use any feature of ParCool.
It might be hard to make wall-jumps and wall slides works correct with Create but make at least crawl.

**Comment by alRex-U** [comment]
I am unfamiliar to the Create mod so I am sure that to support this compatibility will quite difficult.(That mod is great work, absolutely)

As for crawl, could you try again with a config of enabling crawl in air?

**Comment by alinco8** [comment]
Parcool and Create are a truly wonderful combination, so it would be amazing if any issues could be fixed...
