### ISSUE TITLE
First person sprinting arm movement parcool adds messes up the arm position with several mods and their models.

### ISSUE THREAD

**Issue by Jetpack-Cat** [alRex-U/ParCool#121]
**Summary**
Simple summary about the bug

**Running Environment**
+ Minecraft Version: 1.16.5
+ ParCool Version: ParCool-1.16.5-2.0.0.2-R.jar

**Detail**
The first person arm position when sprinting.messes up the visual on several mods. Any mod that adds any kind of glove to the players hand, or mod that adds 3d models gets messed up while sprinting.

Power Glove(artifacts mod) while walking: 
![image](https://user-images.githubusercontent.com/100042170/198847616-095fcf5a-f430-45dc-9de7-1498be1de8a8.png)

Power Glove(artifacts mod) while sprinting:
![image](https://user-images.githubusercontent.com/100042170/198847624-0140a767-f6b9-4782-b8c1-7d988e1f8cab.png)

Crayfish gun mod while walking:
![image](https://user-images.githubusercontent.com/100042170/198847651-aaffe8f1-9515-447c-9538-1e9d4f5ebdae.png)

Crayfish gun mod while sprinting:
![image](https://user-images.githubusercontent.com/100042170/198847658-61e824d7-b2bb-47b1-9805-45a20c9bbda1.png)

suggestion: remove the first person sprinting arm movement parcool adds where the arm moves further back when you're sprinting.

**Comment by alRex-U** [comment]
I know arm animation are applied in first person view but I have wondered why the arm moves during fast-running. Actually parcool only show third person  animation. Research is needed.

**Comment by alRex-U** [comment]
I added conifg item: disable first perview animation.
