### ISSUE TITLE
New move idea !

### ISSUE THREAD

**Issue by COwOkies** [alRex-U/ParCool#122]
Jump on a block to jump higher !

https://user-images.githubusercontent.com/54218300/201410366-36243fda-37d4-46ea-ba2c-4d462af2afc7.mp4

https://user-images.githubusercontent.com/54218300/201410372-6d5a15dd-5b55-4d44-bc10-35bd779d40d2.mp4

![parcool content](https://user-images.githubusercontent.com/54218300/201410382-da4f9d9e-ba4c-4ba3-a1d7-5669485271e3.png)

Similar move in ME :
https://youtube.com/clip/UgkxwTLLbQn4vGbuHracXB6ppdF5fY9UIr3h

**Comment by alRex-U** [comment]
This should be able to be reproduced with Catleap action. I could not come up with convincing reasons that this movement is possible so maybe I do not implement it. Sorry.

**Comment by COwOkies** [comment]
Catleap doesn't jump that high tho

**Comment by alRex-U** [comment]
I know. However I want ParCool to keep real as possible. I think players should look for other paths to their goal if they cannnot reach there with Catleap and Cling-to-Cliff.
