### ISSUE TITLE
Error error, online mode

### ISSUE THREAD

**Issue by DeltDan** [alRex-U/ParCool#125]
**Summary**
Simple summary about the bug
When connecting the server to multiplayer and deactivating the Online mode, the mod simply stops working, it does not allow you to use the abilities that the mod provides.

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: 1.18.2-2.0.0.3-R
+ Forge Version (optional):

**Detail**
When I installed the mod on the server, when the online mode was activated everything was perfect, the bad thing happened when I uninstalled the online mode, the mod did not work, it did not let you run, or climb, or any of the abilities that the mod gives you

**Comment by alRex-U** [comment]
No it is not a bug.

ParCool needs to receive permissions from servers to work. It is also because ParCool work with one installed on server to realize some features.

Thus this mod needs to be installed on server. This fact is also noted on the page of curseforge.

**Comment by alRex-U** [comment]
I maybe should implement it to warn or cannot connect to server if it not installed.
