### ISSUE TITLE
Fast run speed modifier in the config was removed from the latest version

### ISSUE THREAD

**Issue by Jetpack-Cat** [alRex-U/ParCool#133]
mc 1.16.5 ParCool-1.16.5-2.1.0.0-R.jar

The fast run modifier in the config was removed, that was essential to making the player the right speed can you please add it back in. I had it set to 0.7

**Comment by Jetpack-Cat** [comment]
Never mind it was moved to server config

**Comment by alRex-U** [comment]
Yes, it was moved. Sorry, but the internal bugfix needed it move.
