### ISSUE TITLE
[1.16.5 Enhancement] Consider adding Paraglider mod support

### ISSUE THREAD

**Issue by Kaleidio** [alRex-U/ParCool#137]
This is not a bug report thus the template has not been used.

A mod called paraglider exists which provides its own movement stamina system.

This issue simply requests support to:

- use its stamina value instead of your own
- to allow players to choose between UI versions provided by either mod
- allow paraglider and swimming usage provided by the paraglider mod to reduce stamina of parkour

**Comment by alRex-U** [comment]
Hmm, please let me think. I have received this suggestion some times but i ve not decided to do yet

**Comment by Darkmega18** [comment]
seems even kaleidio had the issue where the form would only allow selecting bug and not enhancement? I think you need to check your forms so we can actually apply it later down the line.

**Comment by alRex-U** [comment]
Paraglider mod started to provide its API for stamina so I will add support but the API is only for 1.20.1 now so the support will be also only for 1.20.1

**Comment by Darkmega18** [comment]
alrighty then.

**Comment by Gideon-Yoldov** [comment]
I don't know if Paragliders has made the appropriate changes, but would it be possible to backport the Paragliders support to 1.19.2?  I am building a modpack for that version and it would be much appreciated.
