### ISSUE TITLE
Parcool Doesn't Uses Feathers as Stamina

### ISSUE THREAD

**Issue by Blunder-G** [alRex-U/ParCool#145]
Title :D

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: 3.00
+ Forge Version (optional): 43.2.6

**Additional Data**
![2023-03-02_21 57 03](https://user-images.githubusercontent.com/56030297/222525342-181de0a1-a952-4f83-925e-f1a62ddacc53.png)

I checked the config "Use Feathers as Stamina" multiple times

**Comment by alRex-U** [comment]
ok i'will check

**Comment by alRex-U** [comment]
I checked but it worked. Could you try to play with only Feathers and ParCool once?

**Comment by Blunder-G** [comment]
> I checked but it worked. Could you try to play with only Feathers and ParCool once? Are you installing the latest version of Feathers?

I'm using latest version of the Feathers and i checked it again after you said me to try with only the Feathers and Parcool. It didn't work again

![2023-03-03_17 57 43](https://user-images.githubusercontent.com/56030297/222752970-9a2ed5d7-e864-463a-a1cc-230f1f270675.png)

Did i changed anything to be wrong in Config file? Config file (As Txt Format) : 
[parcool-client.txt](https://github.com/alRex-U/ParCool/files/10883085/parcool-client.txt)

And apart from the issue (or maybe not) i don't why the config file is labeled as "client". It feels like it should be named as "common" or maybe "server" because changes seems like not about visuals or client but how the mod works

**Comment by Blunder-G** [comment]
I don't why but it works now. Strange
