### ISSUE TITLE
Solid Mobs incompatibility 

### ISSUE THREAD

**Issue by ClockworkzAI** [alRex-U/ParCool#149]
**Summary**
Solid Mobs incompatibility 

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version:ParCool-1.19.2-3.0.0.2-R
+ Forge Version (optional): 43.2.7

**Detail**
You cant grab edges or run on walls using these two mods together.

**Additional Data**
Its more of a BUG. I think is the hitboxes between solid mobs and you uses different way of detecting a block that couses a interference between the two mods.
(I am happy and fix the bug more easily if you send me these)

**Comment by alRex-U** [comment]
Thanks for reporting. Ok I will check

**Comment by ClockworkzAI** [comment]
not enough animation  mod  incompatibility also everything works as attended but ladder climbing animation doesn't activate when climbing ladder

**Comment by alRex-U** [comment]
OK I understand the cause. Because of changes by Solid mobs, the game use it's player's bounding box to detect collision though originally it's not done.
