### ISSUE TITLE
Possible bugs?(=>book opening crash)

### ISSUE THREAD

**Issue by KamiSami** [alRex-U/ParCool#15]
Okay, one time more... So there may or may not be bug, feel free to close this if im wrong about this, but since the book doesn't work i cannot confirm if im doing this wrong... But basically in nutshell: Roll and grab cliff does not work at all whatsoever. I am pressing their keybind, and nothing ever happens. I tried run and roll, nothing, roll alone, nothing. I tried to jump next to edge of block and hold grab cliff, nothing, tried to see if it is toggleable, nothing. I always ended up just falling. I did edit the keybind in options, not sure if this has anything to do with it.

**Comment by alRex-U** [comment]
You mean it crashed when you open parcool guide?


[Book Content](https://github.com/alRex-U/ParCool/blob/main/src/main/resources/assets/parcool/book/parcool_guide_content.txt)
This is an internal data of this book.
As far as I read your message, I think maybe you only use these actions with wrong way, in particular about Roll.
If you could not use after reading book, would you tell me it again?
And if it have crashed, Submitting crash reports will make me happy.


I apologize for inconvenience.

**Comment by alRex-U** [comment]
By the way, I thought you might misunderstand "Roll" meaning.


[Parkour Fandom Wiki](https://parkour.fandom.com/wiki/Roll)
I believe it helps you if you are.


Thank you for playing this mod!

**Comment by alRex-U** [comment]
...Did you do GrabCliff while you was holding any Items in your hands?

**Comment by KamiSami** [comment]
Ah! The roll was indeed misunderstanding, thank you for telling me about it, that works. I re-tested also the grab cliff, it works to some extend, but i realized why i probably failed to use it last time... I cannot seem to climb 2 blocks up but i can get if it is 3 blocks. Also about the crash with book... I think it may be related with #11 , but sure, i can paste my crash report, here, i put it in pastebin: https://pastebin.com/3rr6FpTf

**Comment by alRex-U** [comment]
The bug is new one.
I'll try to fix it.

**Comment by alRex-U** [comment]
Upon investigation, it was found that Java type safety was not working.
~~why~~

**Comment by alRex-U** [comment]
Heap pollution?
