### ISSUE TITLE
Server offline i cant use the animations , only offline users can

### ISSUE THREAD

**Issue by fortnitekiddo** [alRex-U/ParCool#150]
**Summary**
Simple summary about the bug

**Running Environment**
+ Minecraft Version:
+ ParCool Version:
+ Forge Version (optional):

**Detail**
Detail about the bug

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)

**Comment by alRex-U** [comment]
Please give me more infomation

**Comment by fortnitekiddo** [comment]
i mean i put in server properties online : false and only offline users can use parcool animations

**Comment by alRex-U** [comment]
When did it occur and which version yoi use. Please follow issue-report template if you use.

**Comment by fortnitekiddo** [comment]
1.19.2 forge

**Comment by alRex-U** [comment]
It is only Minecraft version. I don't want to say like this again and again, but **Please Follow Issue-Report Template** if you use it.

Are you new to use GitHub?

**Comment by fortnitekiddo** [comment]
Animations when i put in server.properties in online = false the animations not working for premium users and only offline users can use animations i mean the mod parcool

Running Environment

Minecraft Version: 1.19.2
ParCool Version: ParCool-1.19.2-3.0.0.2-R

the problem is that , only offline users can use parcool but premium users no

**Comment by alRex-U** [comment]
Thanks for reporting.

Excuse me I want to ask what do you mean with the word "premium user" and "offline user".
Is offline user a player who do not connect to the Internet or Mojang account validation server?
I don't know the existence of account called premium of Minecraft. Just I don't know it?

**Comment by fortnitekiddo** [comment]
i mean offline users are use like a cracked launcher and premium users they buy minecraft normaly

**Comment by alRex-U** [comment]
When the "premium users" open their in-game setting menu(of ParCool, not of Minecraft) by pressing Alt+P and hover their mouse on headers of permission columns("G" or "I"), is an error message shown?

If so I think this can be a clue to fix.
