### ISSUE TITLE
Issues with the mod “controllable”

### ISSUE THREAD

**Issue by TommLowes** [alRex-U/ParCool#153]
Very little works with controllable….. I can do certain things, but most of it is just broken unfortunately! Please make it compatible!   (:

**Running Environment**
+ Minecraft Version: 1.16-1.19
+ ParCool Version: 3.0.0.3
+ Forge Version (optional):

**Detail**
Detail about the bug

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)

**Comment by alRex-U** [comment]
Thanks. However I wanted you to tell more detailed information, such as what "certain things" means.

And now ParCool have received many issues about Controllable, as you can see easily at issues page. Thus let me close this issue. It is not good for lot of same issues to exist.
