### ISSUE TITLE
Controllable incompatible 1.19

### ISSUE THREAD

**Issue by Retrometro89** [alRex-U/ParCool#154]
**Summary**
stuff like cat leap doesn’t work? After I grab on to a ledge I can’t jump up at all. Wall running a bit clunky, cling to cliff Doesn’t work, I’m hoping for a fix? Really enjoy this mod

**Running Environment**
+ Minecraft Version: 1.19
+ ParCool Version:
+ Forge Version (optional):

**Detail**
Detail about the bug

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)

**Comment by alRex-U** [comment]
Thanks but now ParCool have received many issues about Controllable, as you can see easily at issues page. Thus let me close this issue. It is not good for lot of same issues to exist.
