### ISSUE TITLE
[1.18.2] Parcool x Feathers Crawling Compatibility 

### ISSUE THREAD

**Issue by M1DN1GH7** [alRex-U/ParCool#163]
**Summary**
I've discovered that when using both Parcool and Feathers mod, crawling has no affect on stamina consumption. Maybe this can be added as a feature in a future update?

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: ParCool-1.18.2-3.0.0.2-R.jar

**Comment by alRex-U** [comment]
Crawl action does not affect on stamina consumption so also Feathers is not consumed too.

I think you cannot get exhausted by only crawling on ground, right?
