### ISSUE TITLE
[Cross compatibility] Parcool uses paraglider stamina.

### ISSUE THREAD

**Issue by Darkmega18** [alRex-U/ParCool#164]
I noticed that parcool seems to be using my feathers energy that I'd rather keep for elenai dodging. then I realized I had paraglider, and it has a stamina meter also which can be expanded with stamina vessels. it also refills particularly fast to not be a strong limitation compared to using feathers.

Would it be possible to make parcool able to select or automatically detect paragliders and use it's stamina meter?

As far as the consumption rate for feathers is concerned it's rather limiting, as feathers regenerates rather slowly and the maximum also gets reduced if you wear any armor unless configured for this kind of movement and constant use, but then you end up making dodging from elenai dodge overpowered. It might need to be looked at balance wise.

**Comment by alRex-U** [comment]
I am not so willing to do this. Paraglider is not an API for stamina. The reason why I supported Fethers is the mod is explicitly an API for stamina mechanics. I don't want to give mods which are not for API special treatment.
If Paraglider provided API for stamina, I would support it.

And this suggestion is **ENHANCEMENT**, not **BUG**. Please don't use *bug* label.

**Comment by alRex-U** [comment]
Also this issue is duplicated one. (#137) Please let me close this.

**Comment by Darkmega18** [comment]
> And this suggestion is **ENHANCEMENT**, not **BUG**. Please don't use _bug_ label.

I didn't. it would ONLY ALLOW ME TO CHOOSE BUG in the topic choices. there was no "Enhancement" label...

**Comment by alRex-U** [comment]
I see. Indeed, you cannot select enhancement label. yes, sorry. but maybe you selected issue-report template, right? If you wanted to submit enhancement, you could use blank issue.

**Comment by Darkmega18** [comment]
ah, didn't know that was a thing. guess we're both atleast a little in the wrong.
