### ISSUE TITLE
camera animation for horizontal wall run isn't able to be disabled

### ISSUE THREAD

**Issue by Jetpack-Cat** [alRex-U/ParCool#167]
Either this last update or the one before it broke this with my modpack, i'm just now updating the the most recent version and doing a wall run in first-person causes your camera to jerk around. I can't release the modpack with this issue because wall running is a big part of what people do.

![image](https://github.com/alRex-U/ParCool/assets/100042170/293ca792-239e-432a-ad2f-f68d53e9b707)
![image](https://github.com/alRex-U/ParCool/assets/100042170/b04b0f51-09a4-4433-8039-ea014a97fcf6)

**Comment by alRex-U** [comment]
Really? What is your exact version name including minecraft version is?

**Comment by Jetpack-Cat** [comment]
Minecraft 1.16.5
ParCool-1.16.5-3.0.1.0-R.jar

**Comment by alRex-U** [comment]
Ok.

**Comment by alRex-U** [comment]
I checked but it is correctly worked. 
[test video on imgur](https://imgur.com/a/1S9Gkes)

**Comment by Jetpack-Cat** [comment]
https://github.com/alRex-U/ParCool/assets/100042170/6e9e9025-ed68-40c9-8dd0-5d230a061eca

Why is it jerking like this, it didn't used to do this

**Comment by alRex-U** [comment]
This is a change of Wall Run's behavior applied from v3.0.0.0. I have received opinions that Wall Run is quite difficult to use many times. One of the causes was Wall Run didn't lock the camera angle and moving direction, so I did them. I am thinking it may be bacause of forcing the camera to lock angle but 
I don't know why the arm is jerking

**Comment by Jetpack-Cat** [comment]
I absolutely hate this change, it looks bad and it's confusing how the camera locks like this. I have to move back to a previous version or stop using the mod because it's too jarring visually. Could you make a config toggle to turn this behavior off?

**Comment by alRex-U** [comment]
Sorry but now I am working on another non private project so I cannot update this. Thus also I cannot add the config you said. I probably will do it but anyway it won't be done soon.

If you don't want to this mod, I am sad about it but I agree with you if it is necessary for improving your modpack. I wish your project get success.

Can I close or rename this issue?
