### ISSUE TITLE
Frontflipping then grabbing onto a cliff looks silly

### ISSUE THREAD

**Issue by anIceyGirl** [alRex-U/ParCool#17]
A strange bug that occurs when you frontflip towards a cliff and then grab it.

To reproduce:

1. Frontflip towards a 2 block high cliff with both your main hand and off hand being empty.
2. Grab onto the cliff.

Your character should now be spinning in the air until your stamina runs out.

I assume this would also occur when backflipping, but I haven't tested that yet.

Minecraft version: 1.16.5
Forge version: 36.1.16
ParCool version: 1.16.1-1.2.2.10-β

**Comment by alRex-U** [comment]
ah, yes. FrontFlip continue until we land.
And this behavior is clearly bug to fix.
Thank you for reporting!

**Comment by alRex-U** [comment]
Maybe resolved
