### ISSUE TITLE
I need to disable the “climb poles” function, I can't find this setting

### ISSUE THREAD

**Issue by xuanlv797** [alRex-U/ParCool#171]
**Summary**
I need to disable the “climb poles” function, I can't find this setting.

**Running Environment**
+ Minecraft Version:1.19.2
+ ParCool Version:3.0.1.0-R
+ Forge Version (optional):43.2.3

**Detail**
I need to turn off the setting for climb the fence, Because I don't want to keep climbing the fence!!

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)

**Comment by alRex-U** [comment]
There is no config for disabling this action.

Indeed, it may better to add this config. However climbing poles action is implemented differently from other ones. This is why I didn't implemented it when this action was added.

I will do when I have time.

**Comment by alRex-U** [comment]
Done. It will be applied in next update
