### ISSUE TITLE
Mod disables NotEnoughAnimations Ladder climb animations.

### ISSUE THREAD

**Issue by Edoliviro** [alRex-U/ParCool#173]
The animations for ladder climbing do not work with this mod, it resets to the vannila behavior.

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: 3.0.1.0
+ Forge Version (optional):

**Comment by alRex-U** [comment]
Hmm, Ok Thanks for reporting. I will check it later.

**Comment by alRex-U** [comment]
This should be fixed in v3.1.0.0
