### ISSUE TITLE
 Crawn bugs the screen

### ISSUE THREAD

**Issue by Schumacker2007** [alRex-U/ParCool#175]
![2023-06-15_16 12 05](https://github.com/alRex-U/ParCool/assets/107276048/83ae2f48-84fe-45bb-b75f-eeb297a6204d)
![2023-06-15_16 12 05](https://github.com/alRex-U/ParCool/assets/107276048/783c6265-12d0-4ed6-9643-6a8ce1ac1bea)

+ Minecraft Version:1.16.5
+ ParCool Version:ParCool-1.16.5-3.0.1.0-R.jar
+ Forge Version (optional):Forge - 36.2.34

**Detail**
when i crown the screen has that purple and black texture covering everything

**Comment by alRex-U** [comment]
I cannot get what you said exactly. What is the "crown"? ParCool does not add items like crown.

Maybe this is a problem caused by ParCool. You should ask the developer of the mod adding the crown.
