### ISSUE TITLE
origins incompatibility

### ISSUE THREAD

**Issue by baconbaymax** [alRex-U/ParCool#176]
**Summary**
origins incompatibility with wall climbing origins

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: 3.0.1

**Detail**
Whenever using this mod as well as Origins the climbing ability for all origins stop working.

**Additional Data**
if you want a recording I can grab one

**Comment by alRex-U** [comment]
Thanks. Maybe I think climbing pole action may cause.
