### ISSUE TITLE
Sprint jumping at a wall with a drop behind it starts the dive animation

### ISSUE THREAD

**Issue by aaronhowser1** [alRex-U/ParCool#177]
**Summary**

https://github.com/alRex-U/ParCool/assets/15698722/03f42605-a135-4734-8007-ffee5b996c1c

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: ParCool-1.19.2-3.0.1.0-R
+ Forge Version (optional): 43.2.8

**Comment by alRex-U** [comment]
Ah also I noticed it few weeks ago, and already I know the cause. But thanks for reporting.
