### ISSUE TITLE
Incompatible with mekanisem

### ISSUE THREAD

**Issue by robit4** [alRex-U/ParCool#179]
the mekasuit breaks the animations please fix

**Comment by alRex-U** [comment]
Thanks for reporting.

Could you give me more information? Concretely, for example the version of Minecraft, ParCool and Mekanism, and which animation is broken by which items, and screenshot or video showing the bug situation can be grately helpful.

**Comment by robit4** [comment]
![2023-06-25_08 41 45](https://github.com/alRex-U/ParCool/assets/126712560/bae965d8-6b9d-4de0-af0f-12d391617b69)
Here's some evidence

**Comment by alRex-U** [comment]
I think this is because Mechanism overwrite animation. if so I cannot do anything
