### ISSUE TITLE
Incopatibility with Neapolitan´s ¨agility¨ effect

### ISSUE THREAD

**Issue by niconekozilla** [alRex-U/ParCool#180]
**Summary**
Pole climbing breaks Neapolitan´s agility effect, please add the posibility to disable pole climbing in the config.

**Running Environment**
+ Minecraft Version: 1.16.5
+ ParCool Version: ParCool-1.16.5-3.0.1.0-R
+ Forge Version (optional): 1.16.5-forge-36.2.39

**Detail**
It looks like the pole climbing feature overrides the agility effect´s climbing. It is a shame that this happens because Parcool is very compatible for the most part on my personal modpack, even being able to use datapacks to customize my experience with the mod even more thanks to the /parcool command. I hope for being able to choose disabling Parcool´s pole climbing in the config the same way as the other features can be enabled/disabled.

**Additional Data**
c:

**Comment by alRex-U** [comment]
Thanks for reporting.

As you said, maybe ParCool override ladder detection of other mods. I think I can fix for this mod not to unnecessary override for colabolating with other mods, I will try. Of course also I am planning to add config to disable this feature. These update will be released in mid or late August.

**Comment by niconekozilla** [comment]
I´m very glad to hear that, thank you for all your work!
