### ISSUE TITLE
fast run animation stopping

### ISSUE THREAD

**Issue by ManeBOI** [alRex-U/ParCool#182]
**Summary**
fast run and other movement keys don't work well together when used by the same key

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: ParCool-1.19.2-3.0.1.0-R.jar
+ Forge Version (optional): 43.2.0

**Detail**
i have set caps lock as the "parkour key" so cling to cliff, vault, fastrun etc are all the same key. But when i vault, the vault for some reason cancels out the fast  run animation. i still go the same speed but the aniamtion goes away.

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)

https://github.com/alRex-U/ParCool/assets/139763874/b7dedc70-40df-45b6-b453-2e563ecabc1b

**Comment by alRex-U** [comment]
Ah this bug is already found, but Thanks.

This is because fast-run animation is canceled by other animation and not triggered again. I will fix in next version.
