### ISSUE TITLE
(Config Request) Double Tap Fast Run

### ISSUE THREAD

**Issue by FelisMoon** [alRex-U/ParCool#185]
Tapping the toggle sprint key once will initiate sprint normally, tapping a second time will start fast run. Tapping a third time will do nothing.

Basically the mod needs to check if the player is already sprinting, and allow to press the Sprint toggle key again to activate fast run. Minecraft Vanilla does nothing when pressing this key a second time mid sprinting.

**Comment by alRex-U** [comment]
Hmm, ok I will think implementation.

**Comment by alRex-U** [comment]
I did. It will be applied in next update
