### ISSUE TITLE
Strange placing behavior with the mod "accurate block placing"

### ISSUE THREAD

**Issue by Igneo220** [alRex-U/ParCool#186]
**Summary**
Itll like, let you place blocks but only when far away unless you were holding the right click button down when you were starting far away. The behavior is difficult to describe at best, its better you see for yourself

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: 1.18.2
+ Forge Version (optional): 40.2.0

**Comment by alRex-U** [comment]
So what is the problem? I tested but I cannot notice the issue.

**Comment by delveticas** [comment]
> So what is the problem? I tested but I cannot notice the issue.

I'm here the explain the bug, its happening when you try to place blocks when building something resulting of it not placing half of the time, but it goes away after unbinding all of the right click binds from parcool

**Comment by delveticas** [comment]
i use a different mod (pro placer) that does provides features alike and i also stumbled upon this bug

**Comment by alRex-U** [comment]
Could you try again without ParCool after set other keybinds to right click. If this problemis replicated even in this situation, this problem is not ParCool's one.
