### ISSUE TITLE
SUGGESTIONS

### ISSUE THREAD

**Issue by xelotex** [alRex-U/ParCool#188]
The vault really interfieres when you want to jump into a 1 block platform. Example: https://www.youtube.com/watch?v=E_Y6k9swC_8

So, i'm wondering if you can change the vault mechanic so it doesn't vaults whole blocks, and instead it makes you land on top of blocks? This would make the vault move much more controlable and would allow for much precise parkour. I know i could just separate the ledge grab from the vault, which i tried and honestly the ledge grab isnt very responsive, sometimes it works and sometimes it doest, maybe i'm using it wrong? Example: https://www.youtube.com/watch?v=GHSKmhesvBg

And it is much more confortable to have vault and ledge grab in the right click tbh... maybe you should try to make so if the player is holding the jump button, it will always vault (if close to the "upper" part of the block") and ledge grab (if in the "lower" part of the block) and just press the fowards key to climb. Maybe you would have to remove the constant jumping from holding the jump key and the need to hold a key to hold onto a ledge though. Example: 
![parcool](https://github.com/alRex-U/ParCool/assets/70168682/415600d7-9964-4035-a652-4a978247bad9)

Can you make so in order to trigger the cat leap you dont need to be actually running, just need to press the respective sprint button (make it work with both the fast run or the vanilla sprint)? This would be helpful when trying to do the cat leap in a 1x1 platform.

Can you make so in order to trigger the breakfall move, you just need to press it once instead of holding the key? I have the breakfall move binded to the crouch key cause it is really confortable for me, but because of that, i often loose momentum/speed mid air and that really interfieres with my parkour. Maybe you can modify the propeties of the game so the player's momentum doesnt gets penalized for crouching mid air.

**Comment by alRex-U** [comment]
First I have to tell all videos you linked are set as private.
And it is better to separate issues into each one if you have some ideas.

As for the first suggestion that vault should not jump over completely a block, I cannot do that. Vault is a technique to jump over obstacles. If it is just jumping on a block frankly speaking it is not vault, but something else.

The second about vault key binding, you can do that with only features already added. Attach space key to *vault key* and set vault_needs_key_pressed config true.

Then the third, to trigger cat leap with just pressing one key, I also am not willing to do this. Cat leap action make players do quite long jump. Cat leap without running up should seem very unnatural.

The last suggestion may not so bad. I will consider to add it as opt-in one

**Comment by xelotex** [comment]
Understandable, thank u for your time! I fixed the video thing if you want to see them.
