### ISSUE TITLE
error: permissions are not sent from a server

### ISSUE THREAD

**Issue by Swegay** [alRex-U/ParCool#193]
**Summary**
Seems like there is some conflict with another new server modification.

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: 3.0.1.0-R
+ Forge Version (optional): 40.2.10

**Detail**
I have no idea what is the cause. I guess it may be a skin restorer plugin??? but how? didn't test yet

it worked fine, and after adding some new mods it doesn't work now
I still can open a configuration menu and it has red crosses on the right side of the table

**Additional Data**
found nothing but some mixin.parcool notes, seems to be okay

**Comment by Swegay** [comment]
it stopped working as soon as I added
polymorph mod
trumpet skeleton
mob healthbar
and a skin restore plugin

probably it's the plugin?

**Comment by alRex-U** [comment]
could you try again after remove plugin?

**Comment by Swegay** [comment]
yes it works fine without a skin restorer plugin!
still a mystery to me
got tired of these default skins, because server is set to cracked mode
btw thanks for your time and also we love your mod really much
