### ISSUE TITLE
Hang Down Not Working Properly In 1.19.4+

### ISSUE THREAD

**Issue by ChrisLTheNerd** [alRex-U/ParCool#194]
**Summary**
Hang Down does not work 1.19.4+. It only works with version 1.19.3-3.1.0.2-R and bellow, but all the newer versions of ParCool for 1.19.4 and above have the issue, including 1.19.4-3.0.1.0-B.

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 1.20.1-3.1.0.3-R
+ Forge Version (optional): 47.1.43

**Detail**
When you go under chains and end rods with the default key for Hang Down does not work past 1.19.3-3.1.0.2-R and you can't hang like this. 
![parcool_v3](https://github.com/alRex-U/ParCool/assets/50182206/c896eabf-add8-4407-bf86-f6d3cb35da29)

**Additional Data**
Trying to hang onto thin blocks in 1.20.1. Only Cling To Cliff works on thin blocks.

https://github.com/alRex-U/ParCool/assets/50182206/3435b593-3a19-4092-8cf9-24fb1f54f3cc

Settings
![2023-09-14_18 55 41](https://github.com/alRex-U/ParCool/assets/50182206/7d2185b4-241d-46d5-8734-7b1fbd871f22)
![2023-09-14_19 45 47](https://github.com/alRex-U/ParCool/assets/50182206/27daaa7c-1bb2-43ae-bc12-13ee2108eeda)

**Comment by FelisMoon** [comment]
Cannot replicate on MC1.18.2 ParCool V3.1.0.3-R

**Comment by ChrisLTheNerd** [comment]
> Cannot replicate on MC1.18.2 ParCool V3.1.0.3-R Maybe its fixed?

It looks like the issue is only in 1.19.4 ParCool files and above. Thanks for helping figure that out! :)

**Comment by alRex-U** [comment]
Block detection of Hang down is changed for latest versions... I think it cause this
Thanks I will check it

**Comment by alRex-U** [comment]
I notice the cause
