### ISSUE TITLE
Problems in the first 1.12.2 Version of ParCool

### ISSUE THREAD

**Issue by Titoo8899** [alRex-U/ParCool#20]
I have play the new 1.12.2 version of your mod and have find a many Bugs. 

1. The Tutorialbook have in the Tab of your Mod no Texture. You have only the Purpleblack Texture. This must you fix in next 
    Version.

2. The Key W for make a frontflip is for other Parcour thinks not good. I have problems so make other Parcour thinks. Please 
    make a other key for front and backflip please

3. Please make your Tutorialbook better.

**Comment by alRex-U** [comment]
Thank you for test playing and reporting!

I have already checked your 1. item as bug.(#18)

The second proposal, actually FlontFlip keybinding is modifiable. However it is also fact that other Flip and Dodge action's keybinding cannot be changed.
I will consider the new keybinding implementation.

Finally the last one... yes I should improve that.
