### ISSUE TITLE
Can't turn on infinite stamina on a server

### ISSUE THREAD

**Issue by Oleg-burn-inside** [alRex-U/ParCool#204]
**Summary**
Infinite stamina won't be Enabled

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 1.20.1-3.1.0.5-R
+ Forge Version (optional): 47.2.0

**Detail**
I'm playing on Aternos Free Hosting, on the same version of forge and minecraft as i written, and the same version of the mod

In world config file (won't find any other) set "allow_infinite_stamina = true"

On the server stamina still goes down so i checked commands, found command
/parcool limitation get <player> possibility infinite_stamina
and it returns "true" in chat

So i continued to check and found command 
/parcool limitation set <player> boolean AllowInfiniteStamina true
and it returned
[Set 1 player's [allow_infinite_stamina] with true]
but stamina still goes down

So i tried trough server console, same thing, won't work

So i tried to relaunch server, so i shut it down, whet it was off, i checked config, still set to true, then when i launched it, still wont work

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)
sorry, don't have any reports or anything, what i had, i written down, if you need something, please let me know, i'll be happy to cooperate

**Comment by alRex-U** [comment]
`allow_infinite_stamina` is just only allowing infinite stamina, not enabling.
For enabling infinite stamina, Changing config on client is needed

**Comment by alRex-U** [comment]
Please close this issue if the problem is solved

**Comment by Oleg-burn-inside** [comment]
okay, sorry, thank you, wasn't seeing this info anywhere
