### ISSUE TITLE
[suggestion] The stamina system is compatible with mod feathers

### ISSUE THREAD

**Issue by luoxiawuchen** [alRex-U/ParCool#206]
Hello Author, could you please add compatibility with the Feather mod in a future update, 
so that you can choose to use Feather as an stamina value in the options.

Thank you for your patience in reading.

**Comment by alRex-U** [comment]
This is already done. Also for 1.20.1, this feature is planed.

**Comment by luoxiawuchen** [comment]
> This is already done. Also for 1.20.1, this feature is planed.

Thank you for your patient reply.
