### ISSUE TITLE
Add a movement like fast swimming

### ISSUE THREAD

**Issue by betterworld-sjq** [alRex-U/ParCool#210]
The actions on the ground are already complicated.But it seems plain as to moving underwater.Could you add a new movement like fast swimming,which consumes stamina bar to achieve a higher speed in water?

**Comment by alRex-U** [comment]
Ah, actually I can agree. This mod comes from Parkour, the sport on ground so I won't add so complicated action for in-water but such a simple feature may be not bad. I will consider

**Comment by alRex-U** [comment]
[https://github.com/alRex-U/ParCool/commit/e2ee316bf148a9fb1d6ced8cfaae4b8ba7a59a5c](https://github.com/alRex-U/ParCool/commit/e2ee316bf148a9fb1d6ced8cfaae4b8ba7a59a5c)

Done. Applied for next update
