### ISSUE TITLE
My friend dont cant use parcool

### ISSUE THREAD

**Issue by ODenial777** [alRex-U/ParCool#224]
I was playing with my friend in a lan world, but he can't use the parcool mod, but the lightning appears for him, but nothing else works. (we used radmin to get started)

**Comment by alRex-U** [comment]
Please check whether Limitaions are enable.

Or please tell your friend to open in game settings by Alt+P and check if something wrong

**Comment by ODenial777** [comment]
> Verifique se as limitações estão habilitadas.
> 
> Ou por favor diga ao seu amigo para abrir as configurações do jogo com Alt+P e verificar se algo está errado

I forgot to say that when he was a global host I also couldn't use parcool

**Comment by alRex-U** [comment]
Please reopen if this phenomenon is reproduced
