### ISSUE TITLE
Camera rotations are not smooth

### ISSUE THREAD

**Issue by Kogomre** [alRex-U/ParCool#227]
**Summary**
Hi, I wrote to the author of another mod about a problem with the camera in first-person mode, but he also wrote that there is a similar behavior with the third-person camera, I checked and indeed, camera rotations do not work quite smoothly, but with slight jerks. How to solve this problem? Below I will attach an issue where there is a video and a more detailed description

**Additional Data**
https://github.com/xTracr/RealCamera/issues/47

**Comment by alRex-U** [comment]
If I remember correctly FastRunning should have no animation of camera...

Anyway Thank you for reporting.

**Comment by alRex-U** [comment]
Ok maybe I found the cause.

Each animators apply completion to its animation but PlayerModelRotator doesn't.

**Comment by Kogomre** [comment]
@alRex-U Is the problem on your side or on parcool's side?

**Comment by Kogomre** [comment]
@alRex-U this is amazing, when do you plan to release it?

**Comment by alRex-U** [comment]
In near future

**Comment by alRex-U** [comment]
I checked this bug was not appearing with latest build.
This build will be released in few days. I will close this when it released.
Please report if this issue came again
