### ISSUE TITLE
Slide stamina usage config

### ISSUE THREAD

**Issue by Secant1** [alRex-U/ParCool#228]
**Summary**
Changing the stamina consumption value for the slide move in the serverconfig of a world does nothing.

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 3.1.0.6
+ Forge Version (optional): 47.2.0

**Detail**
Limitations imposed was enabled, using paraglider mod for stamina

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)

**Comment by alRex-U** [comment]
Did you set low values than defaults to Limitation?

Limitations is just "limitation". If client wants to do ParCool with low stamina consumption than limitation it set the stamina consumption with limit value, but if not limitation actually don't do anything.
