### ISSUE TITLE
[1.20.1] Random HS Err Pid with parcool wall-jump?

### ISSUE THREAD

**Issue by Baenjamin** [alRex-U/ParCool#230]
**Summary**
Sometimes in creative and survival mode, whenever i try to wall-jump, or even randomly flying around and barely touching a block, i get this random crash.

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 3.1.0.6-R
+ Forge Version (optional): 47.2.20

**Detail**
I'm not completely sure if this is because i use a mod called 'Wall-Jump TXF (Neo/Forge/Fabric)' along with your mod. I might have to try and setting the permit_WallJump to false. Or remove the other mod to see if i can reproduce the bug.

**Additional Data**

HS Err Pid:
[hs_err_pid3368.log](https://github.com/alRex-U/ParCool/files/14265542/hs_err_pid3368.log)

Latest Log: (Don't think the latest log will tell you about this error, but the first one there should.)
[latest.log](https://github.com/alRex-U/ParCool/files/14264669/latest.log)

Also my keybinds:
![2024-02-13_14 25 41](https://github.com/alRex-U/ParCool/assets/20053895/c9afbc72-4a02-4c8b-9469-816b4516b7e4)

**Comment by alRex-U** [comment]
Thanks for reporting.

I want the stacktrace. I think, maybe? the latest.log seems be incomplete. Could you show me the complete log or debug.log file?

**Comment by alRex-U** [comment]
Or its crash-report

**Comment by Baenjamin** [comment]
I did the cheap fix with disabling the walljump from parcool for now. But i started my pack from fresh again and forgot to check here if i needed to get some of the logs from when i crashed. But haven't crashed since at least. So i'll close this for now until i check if i can reproduce the crash. B)))
