### ISSUE TITLE
【Compatibility optimization】It's strange to swing your sword and arm when you run.

### ISSUE THREAD

**Issue by GalaxyZEROX** [alRex-U/ParCool#233]
**Summary**
“ParCool!” There is an action compatibility problem with another MOD“Better Combat ".

**Running Environment*forge*
+ Minecraft Version:1.18.2
+ ParCool Version:3.1.0.6-R
+ Forge Version (optional):

**Detail**
When using the sword of "Better Combat”MOD during Fast Run, the arm will leave the body too much.

**Ad
![2024-03-13_04 07 34](https://github.com/alRex-U/ParCool/assets/73332842/19033129-f758-4833-9258-cc506c4611b5)
![2024-03-13_04 08 26](https://github.com/alRex-U/ParCool/assets/73332842/7cce2e70-ce3f-4ddd-81f7-53c2334226e4)
ditional Data**

**Comment by alRex-U** [comment]
Thanks for reporting. This kind of bugs are sometimes reported I will check later

**Comment by alRex-U** [comment]
This is same issue as #243 so please close this. sorry
