### ISSUE TITLE
[1.20.1 3.1.0.6-R] I hope can auto sky diving and auto divi with jump in water

### ISSUE THREAD

**Issue by NicholasWong-3069** [alRex-U/ParCool#236]
This suggestion is due to a mod called "Smart Moving" https://www.curseforge.com/minecraft/mc-mods/smart-moving-1-12-2
it will auto dose dive posture with waterside on jump in water
and jumping on high location with auto dose skydiving posture

**Comment by alRex-U** [comment]
I cannot understand well...
Could you tell me more a bit?
*dose* is *does*? What is *jump in water* like?

**Comment by NicholasWong-3069** [comment]
my first language is not english I have difficulty expressing
you can watch Smart Moving demo video https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1274224-smart-moving
You can perform diving movements without sprinting & Automatically perform skydiving action

> I cannot understand well... Could you tell me more a bit? _dose_ is _does_? What is _jump in water_ like?

**Comment by alRex-U** [comment]
Ah I see.
However I am not so willing to do it.
ParCool is basically addition, not replacement. Most of parcool actions should have activation condition. The one of dive was to do sprint.
Additionaly I don't think it is not difficult to use current implementation
