### ISSUE TITLE
Flip not working in version 1.20.1

### ISSUE THREAD

**Issue by Kogomre** [alRex-U/ParCool#239]
Forge 47.2.20
ParCool-1.20.1-3.2.0.1-R.jar
Player-animation-lib-forge-1.0.2-rc1+1.20.jar

When i bind button for flip animation and use button animation don't play. And i create video, there you can see strange animation bug, look on right hand character after crawl

https://github.com/alRex-U/ParCool/assets/43267690/8a918ea5-6660-41b6-9821-bb679910fa37

**Comment by alRex-U** [comment]
For now leave the animation aside...

You have to choice flipping control in config.
The default option is "PressRightAndLeft". In this mode, the flip key is not activated.
