### ISSUE TITLE
Dynamic field of view problem

### ISSUE THREAD

**Issue by ainlzj** [alRex-U/ParCool#24]
1.12.2When I load only two modules (parcool. Survivalinc), using sprint causes dynamic vision to expand and contract

**Comment by alRex-U** [comment]
I cann't understand what happened. Would you send screenshots?
Sorry I am not good at English well.

**Comment by ainlzj** [comment]
![1629593089312 00_00_00-00_00_30](https://user-images.githubusercontent.com/66135518/130338448-2b0c5ba9-7864-4753-b569-c730bd36d82d.gif)

**Comment by ainlzj** [comment]
When the original sprint starts, the viewing angle will be closer. When the module sprint is turned on, the viewing angle will be closer and restored

**Comment by alRex-U** [comment]
Ok i'll investigate this problem.
