### ISSUE TITLE
Issues with Crawling in Water + a Possible Enhancement

### ISSUE THREAD

**Issue by zaeonNineZero** [alRex-U/ParCool#240]
**Summary**
Crawling in water is inconsistent and often inconvenient.

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: 3.2.0.0-R
+ Forge Version (optional): 43.3.9

**Detail**
You cannot start crawling while in water, even if you are only slightly touching it (i.e. standing on a waterlogged slab). However, if you enter water while crawling, you will remain crawling until you release the crawl key (PressKey mode) or press it a second time (Toggle mode).

If the crawl input mode is set to Toggle and you press the crawl key while in water, you will begin crawling as soon as you exit the water.

If it is not intended for players to crawl in water, I'd like to suggest changing crawl behavior to **allow crawling in water**. Going into the crawling state in water is a fast and convenient way to begin swimming while at the water's surface, as the player's head will almost always go underwater and thus enable swimming. In this case, you should disable the crawling animation while in water to allow the vanilla swimming animation (which normally plays when crawling/swimming) to play.

**Comment by alRex-U** [comment]
Ah ok. Thanks for reporting.

As you said crawling in water is not intended so ParCool have to cancel it when players enter the water. 

I will fix

**Comment by zaeonNineZero** [comment]
In this case, could you consider **adding a variant of the crawling/prone state** for use in water?

As I detailed above, going prone in water puts the player's head much closer to the water's surface and makes it easier to go underwater - which is required for fast swimming. I think it would greatly improve the usability of fast swimming and water movement in general.

Thanks for responding to the issue by the way!

**Comment by alRex-U** [comment]
For now the bugfix is done.
I put off the enhancement you suggested. I may be going to do in future.
