### ISSUE TITLE
Paraglider stamina usage.

### ISSUE THREAD

**Issue by segic** [alRex-U/ParCool#242]
**Summary**
Parcool's Paraglider stamina usage is odd

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 3.2.0.1-R
+ Forge Version (optional): 47.2.21

**Detail**
The Paraglider stamina usage doesn't work correctly, there's no red bar indicating the stamina is being used currently, also the stamina bar will instantly start recharging as soon as the parkour move is complete, sometimes it'll try recharging it in the middle of the move in fact.

Here's the stamina drain using CravenCrafts Better Paragliders mod, using the stamina as intended:
![bettercombatstamina](https://github.com/alRex-U/ParCool/assets/46935447/5e7f2957-d2ee-41e6-aeef-9bce14fc6165)

and here's Parcools stamina drain:
![parcoolstamina](https://github.com/alRex-U/ParCool/assets/46935447/9ed96eb8-2d17-4a2b-9505-d72baecf252e)

Not the most important thing in the world, but it'd be nice if it could get ironed out, love this mod aside from that, it's perfect!

**Comment by alRex-U** [comment]
Thanks for reporting
