### ISSUE TITLE
ncompatibility Issue between ParCool and Better Combat in Recent Versions 1.20.1

### ISSUE THREAD

**Issue by HeyRicar** [alRex-U/ParCool#243]
I would like to inform you about an incompatibility issue I have encountered between ParCool and Better Combat in the latest versions of Minecraft. While they were previously compatible, attempting to use both mods now results in an error that affects the gaming experience. When performing parkour movements alongside Better Combat's combat mechanics, the game becomes unstable, leading to a bug. I have attached a video clearly demonstrating this issue. I would appreciate it if you could investigate this compatibility problem and find a solution.

https://github.com/alRex-U/ParCool/assets/118484218/ca8d62d0-d3be-474b-bc9b-9179515df4c8

**Comment by alRex-U** [comment]
As for this problem actually I may know why this is caused.

In legacy versions FastRun animation doesn't apply animation to players arm.
But since 3.2.0.1 it does so it may overwrite better combat animation. I think

If so this is just a problem of priority. The simplest solution is decrease priority of ParCool animation (I am sure that Forge should have such API) but this can cause other incompatibilities...

**Comment by zaeonNineZero** [comment]
Better Combat uses the playerAnimator mod for its animations, so you might be able to use that to detect if an animation is in progress. An example regarding this particular issue: detect if an attack animation from Better Combat is in progress, and if so, don't render the Fast Run animation until the attack animation ends.

**Comment by panqueka** [comment]
> Better Combat usa o mod playerAnimator para suas animações, então você pode usá-lo para detectar se uma animação está em andamento. Para este problema específico: detecte se uma animação de ataque do Better Combat está em andamento e, em caso afirmativo, não renderize a animação Fast Run até que a animação de ataque termine.
> 
> EDIT: Este também é o mesmo problema do [nº 233](https://github.com/alRex-U/ParCool/issues/233) e posso confirmar que também está presente no 1.19.2. Imagino que seja um problema que existe em todas as versões do MC e remonta aos lançamentos v3.1.0.0.

How could I do this? I'm having problems because of this mod incompatibility

**Comment by CanecaKun** [comment]
Hello, have any developments been made towards this? i'm playing in 1.20.1 and this compat issue persists

**Comment by alRex-U** [comment]
Please use [ParCool+/Compatibility Addon](https://github.com/[alRex-U/ParCool-CompatibilityAddon](https://github.com/alRex-U/ParCool-CompatibilityAddon))

**Comment by NovaViper** [comment]
@alRex-U Hey is it available to download?  Trying to download it through PrismLauncher but it's not showing up at all on neither Modrinth or CurseForge

**Comment by alRex-U** [comment]
Please download directly from curseforge
https://www.curseforge.com/minecraft/mc-mods/parcool-compatibility-addon
