### ISSUE TITLE
Jittery character model animation not smooth when running fast

### ISSUE THREAD

**Issue by tianwangxiaoyao** [alRex-U/ParCool#244]
**Summary**
Jittery animation of character models in Inventory is not smooth when running fast.

**Running Environment**
+ Minecraft Version:1.19.2
+ ParCool Version:3.2.0.0-R
+ InvMove Mod Version:0.8.2
+ Forge Version (optional):43.3.9

**Detail**
If we want to open and use the Inventory in some way during a fast run (e.g. enable "InvMove Mod"), we will find that the animation of the character model is noticeably unstable in the fast run state.

**Sprint VS Fast Run**

https://github.com/alRex-U/ParCool/assets/125362019/9f86e34c-d878-42dd-88c5-42127f22cd52

Maybe, it's normal.
But whatever it is, I want to make it better, but I don't know how to do it, so if there's a way, please let me know!

**Comment by alRex-U** [comment]
I don't know why this is caused. 
Also I want to fix if possible but the priority is lower because this problem does not occur without such other mods.
