### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YukanurBloodborne** [alRex-U/ParCool#245]
**Summary**
game crashed after i started my world. oddly, it's fine when i play in creative mode
**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: any

**Additional Data**
[crash-2024-04-14_19.07.39-server.txt](https://github.com/alRex-U/ParCool/files/14970740/crash-2024-04-14_19.07.39-server.txt)

**Comment by YukanurBloodborne** [comment]
just found out it has incompatibility with this mod
https://www.curseforge.com/minecraft/mc-mods/actions-of-stamina

**Comment by alRex-U** [comment]
v3.2.0.0 is just released recently so maybe AoS does not support it yet.

There is nothing I can. Please use old versions or ask the developer of AoS
