### ISSUE TITLE
Feathers Compat Broken

### ISSUE THREAD

**Issue by emorydeer2** [alRex-U/ParCool#247]
**Summary**
Simple summary about the bug

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 1.20.1-3.2.0.1-R
+ Forge Version (optional): 47.2.30

**Detail**
Detail about the bug
- Feathers compat isn't working, despite claims.

**Additional Data**
![image](https://github.com/alRex-U/ParCool/assets/107522398/68cf3589-7cc2-4ede-a9af-6d5c6a9626f8)

**Comment by alRex-U** [comment]
Did you enable it

**Comment by alRex-U** [comment]
Please try again after enabling it by config.
If the phenomenon reproduced, please report and reopen this

**Comment by emorydeer2** [comment]
It's enabled.

**Comment by emorydeer2** [comment]
@alRex-U Only collaborators can re-open issues btw.

**Comment by alRex-U** [comment]
Please show me your config

**Comment by emorydeer2** [comment]
```
[Limitations]
	#Whether these limitations will be imposed to players
	limitation_imposed = false

	[Limitations."Action Permissions"]
		permit_BreakfallReady = true
		permit_CatLeap = true
		permit_ClimbPoles = true
		permit_ClimbUp = true
		permit_ClingToCliff = true
		permit_Crawl = true
		permit_Dive = true
		permit_Dodge = true
		permit_FastRun = true
		permit_FastSwim = true
		permit_Flipping = true
		permit_HangDown = true
		permit_HorizontalWallRun = true
		permit_JumpFromBar = true
		permit_QuickTurn = true
		permit_Roll = true
		permit_SkyDive = true
		permit_Slide = true
		permit_Tap = true
		permit_Vault = true
		permit_VerticalWallRun = true
		permit_WallJump = true
		permit_WallSlide = true

	[Limitations.Stamina]

		[Limitations.Stamina."Least Consumption"]
			#Range: 0 ~ 10000
			stamina_consumption_of_BreakfallReady = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_CatLeap = 150
			#Range: 0 ~ 10000
			stamina_consumption_of_ClimbPoles = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_ClimbUp = 150
			#Range: 0 ~ 10000
			stamina_consumption_of_ClingToCliff = 2
			#Range: 0 ~ 10000
			stamina_consumption_of_Crawl = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Dive = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Dodge = 80
			#Range: 0 ~ 10000
			stamina_consumption_of_FastRun = 2
			#Range: 0 ~ 10000
			stamina_consumption_of_FastSwim = 3
			#Range: 0 ~ 10000
			stamina_consumption_of_Flipping = 80
			#Range: 0 ~ 10000
			stamina_consumption_of_HangDown = 3
			#Range: 0 ~ 10000
			stamina_consumption_of_HorizontalWallRun = 2
			#Range: 0 ~ 10000
			stamina_consumption_of_JumpFromBar = 100
			#Range: 0 ~ 10000
			stamina_consumption_of_QuickTurn = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Roll = 100
			#Range: 0 ~ 10000
			stamina_consumption_of_SkyDive = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Slide = 0
			#Range: 0 ~ 10000
			stamina_consumption_of_Tap = 100
			#Range: 0 ~ 10000
			stamina_consumption_of_Vault = 50
			#Range: 0 ~ 10000
			stamina_consumption_of_VerticalWallRun = 150
			#Range: 0 ~ 10000
			stamina_consumption_of_WallJump = 120
			#Range: 0 ~ 10000
			stamina_consumption_of_WallSlide = 8
			#Permission of infinite stamina
			allow_infinite_stamina = true
			#Limitation of max stamina value
			#Range: > 300
			max_stamina_limit = 2147483647
			#Limitation of max stamina recovery
			#Range: > 1
			max_stamina_recovery_limit = 2147483647
```

**Comment by alRex-U** [comment]
Sorry please show me your client config.

**Comment by emorydeer2** [comment]
do you know what the word client means

**Comment by alRex-U** [comment]
In this context "client" means user side of client-server system.

Sorry, did I do something wrong?

**Comment by novaisadumbass** [comment]
Hi! Bumping this. From my testing (1.20.1, ParCool 3.2.0.1-R, Feathers v1.1 B) there really is an incompatibility in the current PC version. In the (client) config the value of _external_stamina_ can only be "None" or "Paraglider", setting it to "Feather" or "Feathers" or anything else prints a warn in the console
> [Thread-3/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file _path_\config\parcool-client.toml is not correct. Correcting

I hope this helps, I really appreciate the mod and the hard work that has been put into it :)

**Comment by alRex-U** [comment]
No, "external_stamina" is old config, your config file contains old items. Please delete the file and restart the game, after that you have to modify "used_stamina" and set it "Feathers"

**Comment by novaisadumbass** [comment]
It indeed works on the latest version! I got my version from modrinth which was not the latest, so that is why the issue happened in the first place. Thank you for help :)
