### ISSUE TITLE
[Animation BUG/ Suggestion] When this MOD is used with Better Combat, the animation of Ctrl Run simultaneously attacking is incorrect

### ISSUE THREAD

**Issue by MoYuEnder** [alRex-U/ParCool#253]
**Summary**
Used with the Better Combat MOD.
Inside the game Ctrl fast running at the same time, the left key attack triggered the arm animation has abnormal twitching.
While the older version(3.1.0.6) of ParCool! The problem did not occur.

**Running Environment**
+ Minecraft Version:1.20.1
+ ParCool Version:3.2.1.1r
+ Forge Version (optional):47.2.16

**Detail**
I love using this MOD with the Better Combat MOD.
(https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)

Especially when the Ctrl is running fast and wielding the weapon (the Better Combat MOD has removed the original attack style and replaced it with an MC dungeon battle animation with rocking back and forth, thus showing the body animation wielding the weapon)

I find it regrettable that in ParCool!   In the old version (3.1.0.6), this would normally trigger the Combat animation without affecting leg running, but in the latest version (3.2.1.1r), strange hand twitching occurred, and the Better Combat MOD's combat animation did not trigger as expected.

(Version 1.8.1 of the Better Combat MOD is used)

**Additional Data**
3.2.1.1r
https://github.com/alRex-U/ParCool/assets/120367297/b3f12fc6-7c30-463b-a616-f1172edc8a3b

3.1.0.6
https://github.com/alRex-U/ParCool/assets/120367297/511bdc7b-8f29-456d-ab1f-a850c7abe707

**Comment by alRex-U** [comment]
Thanks.

This is duplicated issue, check #243.
