### ISSUE TITLE
localization of subtitles missing

### ISSUE THREAD

**Issue by MauritiusChief** [alRex-U/ParCool#256]
**Summary**
Subtitles of sounds don't have localization

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 3.2.1.2-R
+ Forge Version (optional):

**Detail**
localization is simply missing, like "< parcool.sound.dodge" in the game

**Comment by alRex-U** [comment]
Ah Thanks. I have forgotten to add translation. I will do later

**Comment by crispytwig** [comment]
> **Summary** Subtitles of sounds don't have localization
> 
> **Running Environment**
> 
> * Minecraft Version: 1.20.1
> * ParCool Version: 3.2.1.2-R
> * Forge Version (optional):
> 
> **Detail** localization is simply missing, like "< parcool.sound.dodge" in the game

Hi !! I fixed this for Rex under my pull request at https://github.com/alRex-U/ParCool/pull/259 ! If you'd like to give it a look or help me boost it that'd be awesome! ♥

**Comment by alRex-U** [comment]
Thanks, but this issue is for the problem about missing localization, you should have opened new issue
