### ISSUE TITLE
[Crash with pariglider 1.20.1]

### ISSUE THREAD

**Issue by Joshernoob** [alRex-U/ParCool#257]
**Summary**
testing an update of my pack with both mods and when loaded it errors with this mod failed do to

Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.venturecraft.gliders.util.GliderUtil

**Running Environment**
+ 1.20.1 forge 47.2.32
+ ParCool-1.20.1-3.2.1.2-R
+ Paraglider-forge-20.1.3

**Detail**
wpn't load past launch with both installed

**Additional Data**
![Screenshot 2024-05-11 230317](https://github.com/alRex-U/ParCool/assets/64944433/724afc5b-4aa9-42c4-a684-704099d2d791)

**Comment by alRex-U** [comment]
Thanks for reporting
but net.venturecraft.gliders.util.GliderUtil which be shown in the crash-report, seems to be not Tictim's Paragliders mod, 
I searched and this is a class of Jeryn's Gliders mod.
This mod should not have any dependency with this mod but actually this exception is occured in ParCool initialization... it is strange.

Could you try again with only ParCool and Tictim's Paragliders mod, then ParCool and Jeryn's Gliders mod?

**Comment by Joshernoob** [comment]
yes i can try with just the 2 mods installed give me a few second

**Comment by Joshernoob** [comment]
found the 2 mods work together just fine
https://www.curseforge.com/minecraft/mc-mods/epic-fight-integration this seems to be the error thats crashing the mod
