### ISSUE TITLE
Crash with Actions of Stamina

### ISSUE THREAD

**Issue by MistifyedOne** [alRex-U/ParCool#263]
**Summary**
Game crashes immediately when entering survival mod

**Running Environment**
+ Minecraft Version: 1.19.2
+ ParCool Version: ALL Versions, even older ones
+ Forge Version (optional):

**Detail**
Unfortunately, the developer of Actions of Stamina has been missing for a year now, so there is no fixing it on his end. The game crash seems to be caused by the crawl animation of Parcool, and AOS trying to modify it to use the Feathers system along with Parcool trying to as well. A possible fix could be to completely disable crawling when AOS is installed.

**Additional Data**
[Uploading crash-2024-06-12_15.50.16-server.txt…]()

**Comment by alRex-U** [comment]
I cannot see your crash report.... but this kind of problems was sometimes reported.
This issue is actually one of AoS so ParCool cannot do anything and should not.

Though the absence of developer of AoS is sad, we have to wait him to fix it.

**Comment by uuRETCH** [comment]
i'll add on to this -- if you use the 0.4.0 version of AoS, you won't get that crash anymore!
