### ISSUE TITLE
The server disabled Infinite Stamina without any effect

### ISSUE THREAD

**Issue by shaoyouhewu** [alRex-U/ParCool#265]
**Summary**
The server has disabled Infinite Stamina, and the client is not controlled by server rules for Infinite Stamina, can freely switch Infinite Stamina on and off on the client side

**Running Environment**
+ Minecraft Version:1.20.1
+ ParCool Version:3.2.1.2-R
+ Forge Version (optional):47.3.1(mohist server)

**Detail**
`limitation_imposed = true` `allow_infinite_stamina = false` `infinite_stamina = true`

**Comment by alRex-U** [comment]
Thanks for reporting.

Maybe synchronization of limitations has problems by Mohist server? I think

**Comment by shaoyouhewu** [comment]
But I tried it at Vanilla Forge and it was the same

**Comment by alRex-U** [comment]
Oh really? hmm.. I will test it later

**Comment by alRex-U** [comment]
By #270 , the possibility that this issue may be a  problem of synchronization system was indicated so I change the issue title

**Comment by Lainow** [comment]
I've just heard about this problem. Has it been fixed yet?

**Comment by alRex-U** [comment]
I will release 3.3.0.0 in few days.
Please try with it
