### ISSUE TITLE
Super awesome mod, almost perfect it's Smart Movement in 2024, just a few things...

### ISSUE THREAD

**Issue by pobblebonkq** [alRex-U/ParCool#267]
Massively awesome mod, basically Smart Movement reboot done well. I have four gripes though and I think correcting these would make it perfect, I'm sure these are just oversights.

1.) The settings aren't reachable via the mod manager menu so you absolutely have to use shift + p to configure it or use a dedicated key. Not a huge deal but I don't like having unnecessary binds and this is a thing that 99% of other mods have.

2.) Default settings for single player is pretty unbalanced, at least the more basic movement options. I personally don't imagine Steve being all that athletic so I've disabled most of the more acrobatic functions because I mainly wanted a prone mod, but being able to cling to ledges and climb poles and an extra super sprint is cool too. The default stamina rates for even these simple actions are seriously overpowered though, I gotta go into configs to rebalance everything so that Steve cant just sprint like Usain bolt for a solid minute because Steve is definitely not that guy especially in a suit of armor. Max stamina doesn't need to be the max 32 bit value either lol

3.) Given how generous the default stamina settings are, energy drinks are a missed opportunity. Energy drinks are pretty pointless if you can already do so much with default settings, even less so with the poor energy drink if it's an even worse version of rotten flesh. There's no value to doing infinite long jumps in survival if you're just gonna do 3 wall jumps to get up a narrow chasm into a tunnel above you, and any moves more complicated than that you're gonna just wanna build up to in order to be more safe anyways. Here's what I'd do. Instead of "poor quality energy drinks" which is a pretty clunky name, have that just be plain ol "energy drink." Instead of poisoning you and inflicting hunger, have it be like honey where it restores a tiny bit of hunger but instead of curing poison, it instantly refills your energy bar (but it doesn't grant you infinite stamina, or maybe only infinite stamina for a very super short period of time.) Don't need to change anything about what is now called energy drink other than naming it energy *potion* which would be a much more elegant item name scheme imho. Maybe have the actual energy potion inflict hunger for a very short time like the "poor quality energy drink" but not as horrible and not poisonous? That could be a togglable option you could create for it too. BONUS POINTS if you make it so that eating food restores as much in energy as it does hunger, like 2 and a half mutton chops gets you 2 and a half thunderbolts etc. Doing that would actually expand and compliment the default hunger mechanic.

4.) Breakfall stamina consumption is flawed. Either you configure it to use a whole lot and use up your whole bar to stop a 3 block fall from emptying your stamina, or you config it to use very little and falling from 20 blocks can only consume 2 thunderbolts. It would make a whole lot more sense if breakfall consumed as much energy as it saved you health, 1 half heart per 1 half filled thunderbolt, down to emptying all your stamina with 1 health remaining giving you double max fall height. Maybe 1 half heart per one full thunderbolt because feather falling plus break fall could mean you could fall 60 blocks potentially and that's just super silly. Perhaps have a setting that lets you switch from static consumption to consumption as a ratio to health preserved times X configurable divisor/multiplier?

I think if you added these changes it'd be prolly the best parkour mod ever and I'm being super serious, this had a lot of love and care put into it. I feel very strongly enough that adding these features would so greatly capitalize on the potential the framework you created has that I originally commented this on the curseforge page, but IDK how often you check those so I posted it here too, sorry! I can't seem to add the enhancement label here to, sorry for not tagging also. Great job!

1.20.4 for Forge

**Comment by alRex-U** [comment]
Thanks for playing and advising.

1.)
ParCool uses default Forge mod config system. In-game setting is just for modifying it during game. I don't know why we cannot manage it  with mod management menu. What should I do...?

2.)
Yeah current default setting may be quite advantageous for users, but originally these config is all modifiable for users like you, who think this setting is over powered.
Default value have not been changed for long time, so some players feel it annoying if I change them.

3.)
In past, I thought of adding system that players can recover stamina by drinking water. I think this would be sufficient if I added stamina recover item.
And you seem to regard energy drinks pointless, but the max stamina of max 32bit value is acutally a limit given by server, not actual value. This limit may be various for each servers. Energy drink has an aspect that enables players to perform without attention to stamina even in servers which set max stamina value 500.
As for renaming item, please let me think for now 

4.)
Hmm about this I want to consider a bit..
