### ISSUE TITLE
Some configurations should not be placed in the client configuration

### ISSUE THREAD

**Issue by Dr-WeiAL** [alRex-U/ParCool#270]
**Summary**
As the title says, there is a lot of configuration in parcool-client.toml that looks like it should be in parcool-server.toml.

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 3.2.1.2-R
+ Forge Version (optional): 47.2.20

**Detail**
There are too many, for example Stamina related configurations that should not be in the client, and the consumption rate modified in the client will ignore the configurations in server

**Additional Data**
![image](https://github.com/alRex-U/ParCool/assets/47446553/f2963ea7-b257-4944-ac1c-6f1e41bcd719)
![image](https://github.com/alRex-U/ParCool/assets/47446553/22d6606b-fb77-4689-a252-8ac0b4f7a132)

**Comment by alRex-U** [comment]
Configs in server are global limitations. 
Also the stamina consumptions of server config are just least values, it make no effects on actual value when consumption which is set on client is larger than server one.

Client config includes just only client settings such as about gui, and controls. These setting should not be in server setting.

Or, what you wanted to say was other things?

**Comment by Dr-WeiAL** [comment]
When I set Fast Run to 25 on the server side and 0 on the client side, the client can run all the time without consuming Stamina
This clearly doesn't take precedence over server-side settings, and I don't seem to be the only one reporting this type of problem.

I don't think settings like Stamina consumption should be in the client settings, but only in the server side

**Comment by alRex-U** [comment]
Ah, recently an issue of synchronization of Limitations was reported with 1.20.1
#265

So this may be the cause of that problem.

> I don't think settings like Stamina consumption should be in the client settings, but only in the server side
In fact I can agree this opinion but some players want change these values for each players in multiplayer game. On the other hand, other players want to modify client behavior from server
Limitation is a kind of desperate solutions for this problem.
I hope for your understanding.

**Comment by Dr-WeiAL** [comment]
Well, it's good to find out what the problem is.
