### ISSUE TITLE
Replacing Sprint with Fast Run

### ISSUE THREAD

**Issue by scarls686** [alRex-U/ParCool#273]
I know there is an option for "substitute sprint" in the settings,but this is not what I want.This only allows me to complete the action while sprinting, and if I need to fast run, I still need to hold down Ctrl.
I hope to replace sprint with fast run, just like the old version did.Moreover I hope the slide will not interrupt the fast run.

**Comment by alRex-U** [comment]
Please set `FastRunControl` with Auto
