### ISSUE TITLE
Where's the goddamn Fabric version?

### ISSUE THREAD

**Issue by lucashsantosb** [alRex-U/ParCool#282]
Everyone is asking for that, why limit your mod for only a loader? Just create a API so it'll easily possible to you to convert your versions between loaders.

**Comment by amzelee** [comment]
Another day another entitled comment. Devs are in no way obligated to do this lol.

**Comment by alRex-U** [comment]
Thanks, but I have no plan to port to fabric API
Even maintaining current Forge versions has some troubles. Maybe I cannot take time to continue to support and maintain Fabric versions.
Also as for making API for port to other mod loaders I'm sure that it cost too much to make comprehensive API over this mod.
Sorry
