### ISSUE TITLE
suggestion: make hwall run auto mode only work when holding space

### ISSUE THREAD

**Issue by VaporeonScripts** [alRex-U/ParCool#292]
**Summary**
when ur walking into a wall,u have to hold space to walk on that wall, otherwise its annoying cuz it always auto walks there and its hard to move

**Running Environment**
+ Minecraft Version: 1.21.1
+ ParCool Version: latest
+ Forge Version (optional): neoforge 1.21.1 .61

**Comment by alRex-U** [comment]
Set `h-wall-run_control` by `press-key` and set Horizontal Wall Run keybind with Space

**Comment by VaporeonScripts** [comment]
Thing is there isn't the keybind😭
