### ISSUE TITLE
the config file did not generate

### ISSUE THREAD

**Issue by blikthepro** [alRex-U/ParCool#294]
**Summary**
parcool-config.toml did not generate when loading the mod on a server

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 3.3.0.1-R
+ Forge Version (optional): 47.3.10

**Detail**
i am running the server on an oracle vm with java 21. cannot find the config file nor the serverconfig folder that the mod refers to

**Additional Data**
everything runs fine otherwise, just that i can't tune the mod serverside

**Comment by alRex-U** [comment]
The config file for server is only `parcool-server.toml`. `parcool-config.toml` is not generated
