### ISSUE TITLE
mod doesnt work on server

### ISSUE THREAD

**Issue by VaporeonScripts** [alRex-U/ParCool#306]
**Summary**
https://mclo.gs/RfwgBR1
**Running Environment**
1.21.1
latest
neoforge .72

**Detail**
https://mclo.gs/RfwgBR1
**Additional Data**
https://mclo.gs/RfwgBR1

**Comment by alRex-U** [comment]
Thanks for reporting

**Comment by VaporeonScripts** [comment]
No problem

**Comment by VaporeonScripts** [comment]
please push the fix, its a simple 1 line code, i cant start my server without it :D 
![image](https://github.com/user-attachments/assets/246da626-9a22-4822-a99a-3e7548c92eec)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/14358126-58ec-46f2-bd1d-13a07f9d6d65)

**Comment by Rarity1** [comment]
I patched it myself if you want to build the fork I made. I had to change a lot of stuff around because I didnt know how it worked. I really wanted to use it on my server

**Comment by alRex-U** [comment]
Fixed at v3.3.0.3. Thank you
