### ISSUE TITLE
server side issues (neoforge 1.21.1 .76)

### ISSUE THREAD

**Issue by VaporeonScripts** [alRex-U/ParCool#316]
**Summary**
title
**Running Environment**
+ Minecraft Version: 1.21.1
+ ParCool Version: latest
+ Forge Version (optional): 21.1.76

**Detail**
![image](https://github.com/user-attachments/assets/c3cb6642-bd39-4b5d-9e3c-92f604ea213a)

**Additional Data**
![image](https://github.com/user-attachments/assets/c2636db3-da0d-49ad-857b-4cb9b981b526)

**Comment by alRex-U** [comment]
I tested but such problem was not reproduced.
Could you try again with latest version (v3.3.0.4)?

**Comment by alRex-U** [comment]
When did this bug occur?

**Comment by VaporeonScripts** [comment]
the bug got fixed time ago iirc, it works fine
