### ISSUE TITLE
make stamina light mode icons a lil bit higher

### ISSUE THREAD

**Issue by VaporeonScripts** [alRex-U/ParCool#317]
1.21.1 neoforge .77
cuz it overrides a stamina part from iron spells

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/6d69f6f7-a684-4ba2-b1bb-06825b9c850b)

**Comment by alRex-U** [comment]
I feel it is Iron Spells's failure...
Please use option to modify position of HUD in config

**Comment by VaporeonScripts** [comment]
wheres that option? cant find it

**Comment by alRex-U** [comment]
named as `offset_<_>_light_hud`

**Comment by VaporeonScripts** [comment]
bro where tf is that option,i cant find it bruhhh
