### ISSUE TITLE
charge jump & sneak jump bugged

### ISSUE THREAD

**Issue by RuafuMan-Obs** [alRex-U/ParCool#318]
**Summary**
charge jump & jump bugged on inverting ctrl/shift keybind

**Running Environment**
+ Minecraft Version: 1.20.1
+ ParCool Version: 3.3.0.2
+ Forge Version (optional): 47.3.0

**Detail**
I inverted the keybind of sneak/run ; shift to run , ctrl to sneak , when holding ctrl i can do neither charge jump or normal jump ,even i disabled the charge jump , set toggle to sneak instead of hold can fix this ,but it makes character control feel so bad

**Additional Data**
Such as Screenshots or Crash Reports
(I am happy and fix the bug more easily if you send me these)

**Comment by alRex-U** [comment]
I tested but such problem was not reproduced.
Could you try again with latest version (v3.3.0.4)
