### ISSUE TITLE
How to disable this shifting animation

### ISSUE THREAD

**Issue by Foxsik193** [alRex-U/ParCool#320]
![Снимок экрана 2024-11-19 220906](https://github.com/user-attachments/assets/b379f766-71ad-4013-b361-4bb8b2cca986)
Personally, this animation pisses me off is there a way to disable it in config? if so, drop the name of it, I just can't find it

**Comment by ElTormakzXD** [comment]
You can only disable all animations, I don't know any other way.

**Comment by alRex-U** [comment]
This is charge jump, you can disable it or its animation in config
