### ISSUE TITLE
Server can't start

### ISSUE THREAD

**Issue by ElenaNya** [alRex-U/ParCool#336]
**Running Environment**
+ Minecraft Version: 1.21.1
+ ParCool Version: ParCool-1.21.1-3.3.0.2-NF
+ Forge Version (optional): NeoForge 21.1.83

**Additional Data**
[crash-2024-12-06_15.03.02-fml.txt](https://github.com/user-attachments/files/18039128/crash-2024-12-06_15.03.02-fml.txt)

**Comment by alRex-U** [comment]
please use latest version

**Comment by ElenaNya** [comment]
Oh, sorry, didn’t notice that the latest version is on CurseForge, not on Modrinth. Thank you
