### ISSUE TITLE
Unexpected Rolling Animation in modded server

### ISSUE THREAD

**Issue by alRex-U** [alRex-U/ParCool#37]
It seems that rolling animation continue when it is played in multi player game with modded server.
[Bug report](https://www.curseforge.com/minecraft/mc-mods/parcool?comment=97)

**Comment by ThePieTheory** [comment]
I've recently found this exact bug in my modded servers. It seems like the animations continue to loop as long as either of the "Flipping" animations were just executed. It's possible to get these animations to cease through doing either of the left or right dodge actions. I'm able to get consistent reproduction although I haven't found the exact cause for this issue.

**Comment by alRex-U** [comment]
Thanks!
I maybe misunderstood the action of this bug as Roll.
The cause must be a mistake about synchronization(but i cannot come up with why this occurs soon).
Recently i made a commit to re-implement action classes. I hope that this bug has been fixed.

**Comment by alRex-U** [comment]
It would be best if I could test this

**Comment by alRex-U** [comment]
I finished test
