### ISSUE TITLE
I crashed when I used parcoolmod to connect with my friends online

### ISSUE THREAD

**Issue by ainlzj** [alRex-U/ParCool#43]
[crash-2022-01-26_18.50.22-client.txt](https://github.com/alRex-U/ParCool/files/7941225/crash-2022-01-26_18.50.22-client.txt)

**Comment by alRex-U** [comment]
Thank-you for reporting!
The Parcool in 1.12.2 have not been tested on multi players game yet.
A Class Cast Exception, it is not very difficult to solve this but now i am working on a parcool in 1.16 so i cannot do soon.
I am sorry to trouble you.
