### ISSUE TITLE
animation rendering on multiplayer/local host

### ISSUE THREAD

**Issue by LordGriefington** [alRex-U/ParCool#55]
**Summary**
Odd rendering for some animations in miltiplayer. arms on the wrong player, infinite back-frontflip

**Running Environment**
+ Minecraft Version: 1.16.5
+ ParCool Version: 1.2.2.11-R
+ Forge Version (optional): forge-1.16.5-36.2.20
+ OptiFine_1.16.5_HD_U_G7 / ComplementaryShaders 3.09

**Detail**
when one player is doing a flont or backflip. they will sutck in that animation, but for other players. until the flipping player is using strafe light or right.
if other players are shown on your screen, while they are climbing, you see them with no arms, but their arms will get added additional to your skin, in climbing position.
(on single player I have it combined with the fight mod, only imcompatible issue are 4 arms while climbing in combat mode.
if you wamt to fix this together EpicFightMod-16.5.13 owner: maninthe_home) 

**Additional Data**
![out of sight](https://user-images.githubusercontent.com/83673600/156908253-15e1ab4c-5ab6-42d3-9ea1-2c6546f3bded.PNG)
![in sight](https://user-images.githubusercontent.com/83673600/156908254-d187f8eb-c907-43cb-89b2-7ef957080f22.PNG)
https://cdn.discordapp.com/attachments/847998484946354177/949871385310797874/bugreport.gif

**Comment by alRex-U** [comment]
Dont mind.
I will release new version(1.4.0.1-R) soon, this bug is fixed in the version.

**Comment by alRex-U** [comment]
soon
