### ISSUE TITLE
I keep crashing when dying since installing the mod

### ISSUE THREAD

**Issue by Niko1811** [alRex-U/ParCool#59]
[crash-2022-03-15_14.52.53-client.txt](https://github.com/alRex-U/ParCool/files/8253957/crash-2022-03-15_14.52.53-client.txt)

Edit: It only crashes in first person, which makes me believe that it's something with the first person model mod... which would be sad cuz these mods together are just perfect

**Comment by Niko1811** [comment]
It's weird cuz It works without ParCool just fine so idk
I could do a little more testing and If i find anything new I'll just send it here

**Comment by Answordy** [comment]
Got same crash after installing the latest version of the mod today

**Comment by alRex-U** [comment]
Oh, the version do not include this bugfix.


Did you install First-Person Model mod in the same time? It is reported that this co-existance is the cause.

**Comment by MMVVMM** [comment]
1.16 got the same crash using the latest version

**Comment by alRex-U** [comment]
Sorry, the latest version did not fix this bug because it might take quite much time.

**Comment by alRex-U** [comment]
I updated this mod with more safe methods. If this bug reproduced, please re-open an issue.
