### ISSUE TITLE
[Bug 1.16.5] Right-Clicking on door while nearby a fence will change camera angle.

### ISSUE THREAD

**Issue by Augusto2103** [alRex-U/ParCool#61]
Ok, so this is what happens:
Let's say I'm "inside" a fence block (basically, stepping on the same block the fence is on), then I wish to open / close a door that is behind me, so I right-click, then it closes the door, but instatly obligates my camera look contrary to the door.
Edit: Found another one, it's one about crawling and rolling. It seems that the rolling keybind is mixed with the crawling one and both actions cannot have different keybinds. It's as if I put R for rolling and C for crawling, and I try to use roll with R but won't do anything, but when I do C, it does activate the rolling event.

Also, I'm the same person to list the ideas of possible improvements and that told you about the bstylia14 video in the CurseForge page, keep it up pal!

**Comment by alRex-U** [comment]
Thank-you for reporting.


The second issue is already opened, and already fixed as for 1.18. Please check.


Then, I cannot understand the situation though I think maybe something strange happened. Could you add anything like images or videos?

**Comment by Augusto2103** [comment]
![2022-03-21_19 09 44](https://user-images.githubusercontent.com/99851797/159371823-03f19e7c-b261-4b93-9163-af7d81a51147.png)
![2022-03-21_19 09 37](https://user-images.githubusercontent.com/99851797/159371836-42ad326b-c091-48a0-86ea-2c0e1e4b67dc.png)

**Comment by Augusto2103** [comment]
Also, if possible, I believe it would be appreciated if the fix from 1.18 could be passed onto 1.16.5

**Comment by alRex-U** [comment]
I think this is correct behavior. Cling-To-Wall ability make the players facing to the walls.
In this situation, ParCool regarded the fence as a wall. I will fix but it takes more time to pass onto 1.16.5

**Comment by Augusto2103** [comment]
Seems very good, thank you for your time!
