### ISSUE TITLE
1.18.2-1.0.0.0-R: Mod fails to work properly on dedicated server

### ISSUE THREAD

**Issue by deadlymango** [alRex-U/ParCool#63]
**Summary**
I installed ParCool onto my server with my indev modpack. The server starts up, as well as the client which is sharing the same set of mods. However, when the client attempts to connect to the server, the connection gets reset, with the following error showing up in the server console:
`Attempted to load class com/alrex/parcool/client/animation/Animator for invalid dist DEDICATED_SERVER`

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: ParCool-1.18.2-1.0.0.0-R.jar
+ Forge Version: 40.0.24

**Detail**
It sounds like the animator class is getting called to run on the server when it should not be.

Just to confirm, I installed ParCool on the client side only and attempted to connect to the server. Server rejected the client with mismatched mod list. 

**Additional Data**
https://gist.github.com/deadlymango/f47fe64be3414ecf433b09ac8f7ff95b
You want to look at the logs starting from line 3131.

**Comment by alRex-U** [comment]
Thank-you for reporting!

It seems to be not so difficult error. I think it will not take so much tike.
