### ISSUE TITLE
Weird Arm Behavior

### ISSUE THREAD

**Issue by CatalystGinger** [alRex-U/ParCool#68]
**Summary**
Simple summary about the bug

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version:  ParCool-1.18.2-1.0.0.1-R
+ Forge Version (optional): Forge_40.0.25-OptiFine_H6

**Detail**
Catleap,vault and rolling.
After using these three movements, the walking posture becomes to move his foot and hand same side."Shunguai"
After exiting the game and re-entering, it is normal. If I use these three actions again, it will become this strange posture.

**Additional Data**
![2022-03-26_15 03 08](https://user-images.githubusercontent.com/98942977/160278165-fb1e011a-217e-41ef-b1fa-31c311350e2d.png)

The game doesn't crash.
![2022-03-26_15 03 09](https://user-images.githubusercontent.com/98942977/160278171-7cfbb47f-e265-4db9-881d-1033a073c717.png)

**Comment by alRex-U** [comment]
I am now sure that the cause of this bug is that the legs is swapped. I made a mistake about resetting their position

**Comment by alRex-U** [comment]
I have a plan to fix this in 1.16.5,1.18.2 for now
