### ISSUE TITLE
[1.18.2] Rendering/visual oddity when performing catleap while wearing armor

### ISSUE THREAD

**Issue by deadlymango** [alRex-U/ParCool#78]
**Summary**

If the player is wearing armor (especially boots and leggings), when performing a catleap, both the player's legs will render the way they do during a normal catleap, but player can also see the boots and leggings move back and forth like in vanilla. This creates a strange appearance where the player appears to have four legs in the air. Two legs with the armor are moving back and forth like normal, while two unarmored legs are staying still using the catleap animation. 

If the Epic Knights mod is installed, which provides armor that covers the arms with its chestplates, one can see the same behavior with the arms as with the legs.

**Running Environment**

Minecraft Version: 1.18.2
ParCool Version: ParCool-1.18.2-1.0.1.0-R
Forge Version: 40.1.0

Using an indev modpack. Possible conflicting mods:
Rubidium (Sodium for Forge)
NotEnoughAnimations (just tested; issue remains even with this mod removed)

**Detail**

I have not delved into the code to provide a definitive fix. However, I did see options to disable certain animations in the parcool-client.conf file, in particular the backflip and frontflip dodge animations, as well as the "Kong Vault" animation. 
As a bandaid fix, perhaps you could look into adding another config option to disable the catleap animation? Or, a better fix would be to figure out how to render the player's appearance when armor is worn.

**Additional Data**

Video demonstration here: https://files.catbox.moe/4mqw64.mp4

**Comment by alRex-U** [comment]
Thank you for reporting!

Yes, this is an known bug. ParCool do not overide the rendering armor animations. This is because i do not know how to do that. 

I want to try again to fix this. however I do not know whether it will goes well.
Sorry for my lateness.

**Comment by alRex-U** [comment]
I fixed.
