### ISSUE TITLE
Vault Jumping when going up a staircase

### ISSUE THREAD

**Issue by GeradesoLukas** [alRex-U/ParCool#80]
**Summary**
When running up a staircase, you vault jump at the end. This is kind of annoying over time. Hope you will find a fix for that ^^"

**Running Environment**
+ Minecraft Version: 1.16.5
+ ParCool Version: 1.16.5-1.4.1.0-R

**Comment by alRex-U** [comment]
Thank-you for reporting!

I know this bug. However I did not fix because it is quite difficult to distinguish an end of stairs from vault-able steps.

**Comment by GeradesoLukas** [comment]
I would have a suggestion on how to fix it:
You could make it, so the player has to press the grab cliff button while running. This would ensure, that it only happens, when needed. I think this button would be the best, because you don't normally use it while running.

**Comment by alRex-U** [comment]
Ok, I will test it, but i worry it will be something annoying.

**Comment by alRex-U** [comment]
I implemented vault keybinding (defaultly same as cling-to-cliff key)
It will be applied to next update
