### ISSUE TITLE
[Suggestion] Use obfuscate for the animations

### ISSUE THREAD

**Issue by GeradesoLukas** [alRex-U/ParCool#82]
Hey, so I know this might be a big step, but I think it could be very helpful. The library by MrCrayfish seems to have all the needed features to make cool animations for parcouring. 
This might also help to fix the dodge-flip, that looks weird from certain angles (I hope this is a known issue)
This might require a bit of rework, but it might be worth it in the end.

I hope this idea might help, I wish you a great day/evening ^^

**Comment by alRex-U** [comment]
Actually, I am now planning big re-implement the inner structure, mainly animations. Thus I consider which way i use, including obfuscate.

I am on phase of testing those means. However also I'm quite busy now, so it may take a few month.

**Comment by alRex-U** [comment]
In addition, Obfuscate support 1.18+ no longer. He suggests to use Framework instead. I  also have to check the compatibility between them.

**Comment by GeradesoLukas** [comment]
Okay, good to know. I hope you will find a solution that fits your needs ^^

**Comment by alRex-U** [comment]
Maybe Framework do not support custom animations.
However, I got an better idea from it. Using Spongepowered Mixin directly is
