### ISSUE TITLE
Cliff hanging doesn't stop fall damage

### ISSUE THREAD

**Issue by iMazariuz** [alRex-U/ParCool#83]
**Summary**
Simple summary about the bug

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: 1.0.1.0-R
+ Forge Version (optional): 40.1.0

**Detail**
If you fall and then cliff hang, and then release, you will get fall damage as you land, as if you didn't cliff hang at all.

**Additional Data**
https://drive.google.com/file/d/11P57tmqVQHoOQlrkI-3GphSTZy0FUXE_/view?usp=drivesdk
(Vid demonstrating the bug)

**Comment by alRex-U** [comment]
Thank-you for reporting!

Ok, I want to check this problem.

**Comment by alRex-U** [comment]
Good Contribution, Thank-you!
