### ISSUE TITLE
Crash with PlayerRevive

### ISSUE THREAD

**Issue by ShenxPresent** [alRex-U/ParCool#84]
**Summary**
when using PlayerRevive mod at same time, once player dying, the game will crash

**Running Environment**
+ Minecraft Version: 1.16.5
+ ParCool Version: 1.4.1
+ Forge Version (optional):

**Comment by ShenxPresent** [comment]
> 

yes, but different mod

**Comment by alRex-U** [comment]
Could you show me your crash report if possible?

**Comment by alRex-U** [comment]
I updated this mod with more safe methods. If this bug reproduced, please re-open an issue.
