### ISSUE TITLE
Crash when dead

### ISSUE THREAD

**Issue by Dev001L** [alRex-U/ParCool#87]
My game is crashing when i get the death screen, when i crash my world corrupts entirely and i can't load it anymore, making all of my maps like hardcore.

I tried to reload all my mods one by one and i got to discover that this mod is having some sort of incompatibility with one of my mods. I have a lot of mods so idk

The crash report says that my map or even my game have incompatibility with ALL OF MY MODS

If you want the crash report text, i can send it.

**Comment by alRex-U** [comment]
I am sorry for this inconvenience. I received some similar crash(#59,#84)(one suggested mod which have incompatibility is First Person Model mod) but I have never received a report that the game cannot be loaded.

Could you show me the crash report? I apologize for my lateness.

**Comment by faddanicolo** [comment]
I'm having the same problem, it only happens when I have shaders (oculus mod) turned on, here's the log
[2022-07-28-1.log](https://github.com/alRex-U/ParCool/files/9204574/2022-07-28-1.log)

**Comment by alRex-U** [comment]
I came up with one of the causes being able to be thought.

This mod operate rendering matrix stack. Then if other mods canceled the event where parcool push the stack, and this only pop it, your crash report could occur.

**Comment by faddanicolo** [comment]
Is there anything I can do/help with to solve the issue?

**Comment by alRex-U** [comment]
I updated this mod with more safe methods. If this bug reproduced, please re-open an issue.
