### ISSUE TITLE
Not working in Multiplayer Server

### ISSUE THREAD

**Issue by ZombieAki** [alRex-U/ParCool#88]
**Summary**
The mod looks not working in my server but it works well in singleplay. 

**Running Environment**
+ Minecraft Version: 1.18.2 
+ ParCool Version: 1.18.2-1.0.1.0-R
+ Forge Version (optional):Client-40.1.68, Server-40.1.59

**Detail**
Both client and server(arclight core) installed the mod. I can find endurance bar and get guide book from JEI in game. But I can't do any added parcool actions. No configuration files were generated in the server directory, and no crash reports founded in console.

**Additional Data**
![QQ截图20220812190037](https://user-images.githubusercontent.com/19723289/184341438-103381d3-3771-457e-ae0a-55d715fcb2f3.png)
![QQ截图20220812190046](https://user-images.githubusercontent.com/19723289/184341445-0b7b82aa-2b39-421c-b9ea-77a391575cd6.png)

**Comment by ZombieAki** [comment]
The Nether

**Comment by ZombieAki** [comment]
After entered the nether, the mod suddenly works well and keep working.
I still not known what happened.

**Comment by alRex-U** [comment]
The behavior seems like the one that occurs when the mod is not installed in a server.

I think maybe the server failed to send action permissions to your client(this mod do not allow any action if the permission is not received). Probably the permission was re-sended when you entered nether. However I do not know why the configuration not generated.
