### ISSUE TITLE
Incorrect third-person animation maths

### ISSUE THREAD

**Issue by jf908** [alRex-U/ParCool#89]
**Summary**
The math is incorrect for the third-person model, it works when the camera is looking horizontally but not when it is looking upwards or downwards.

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: 1.0.1.0
+ Forge Version (optional): 40.1.73

**Detail**
The larger the pitch value is, the less the animation has an effect. This effect is easiest to see when you are doing a front flip but it happens with all third-person animations.

**Additional Data**
It is correct when camera pitch = 0 degrees.
![2022-08-17_20 13 16](https://user-images.githubusercontent.com/2487520/185223642-b16f3015-2f70-4712-b17c-502ff722005f.png)

It is incorrect when camera pitch = 90 or -90 degrees, it doesn't look like I am spinning.
![2022-08-17_20 13 20](https://user-images.githubusercontent.com/2487520/185223885-c756da8a-6f27-4752-a51f-a0a03589f377.png)

**Comment by alRex-U** [comment]
It have already been fixed. Next update will apply this patch.

**Comment by jf908** [comment]
Thank you! Great mod 👍
