### ISSUE TITLE
Crash in LAN

### ISSUE THREAD

**Issue by AlisterGontineac** [alRex-U/ParCool#9]
[Minecraft Java 1.16.5 Crash Report.txt](https://github.com/alRex-U/ParCool/files/6533705/Minecraft.Java.1.16.5.Crash.Report.txt)

**Comment by alRex-U** [comment]
Thank you for submitting crash reports!

**Comment by alRex-U** [comment]
It may be fixed at latest α version, please try it.

**Comment by alRex-U** [comment]
Close since there was no reply.
