### ISSUE TITLE
Incompatible with kubejs

### ISSUE THREAD

**Issue by SeanChengN** [alRex-U/ParCool#95]
**Summary**
Crash on startup when installed at the same time as kubejs, But ParCool-1.18.2-1.0.1.0-R works fine.

**Running Environment**
+ Minecraft Version: 1.18.2
+ ParCool Version: 2.0.0.0-R
+ Forge Version (optional): 4.1.69

**Detail**
architectury-4.9.83-forge
kubejs-forge-1802.5.4-build.533
ParCool-1.18.2-2.0.0.0-R
rhino-forge-1802.1.14-build.225

Tested with only the above 4 mods, kubejs and its dependency.

**Additional Data**
https://pastebin.com/PxsZxqKz
I run on server and export logs, same error as client.

**Comment by alRex-U** [comment]
Thank you for reporting.
Now I am working to fix these incompatibilities problem. Please wait.
