### ISSUE TITLE
Incompatible with balm

### ISSUE THREAD

**Issue by supershorty1** [alRex-U/ParCool#96]
**Summary**
Crash on startup with ParCool-1.18.2-1.0.1.0-R and balm

**Running Environment**
+ Minecraft Version:1.18.2
+ ParCool Version:2.0.0.0-R
+ Forge Version (optional):40.1.73

**Detail**
balm-3.2.0
ParCool-1.18.2-2.0.0.0-R

**Additional Data**
[latest.log](https://github.com/alRex-U/ParCool/files/9388307/latest.log)

[debug.log](https://github.com/alRex-U/ParCool/files/9388308/debug.log)

**Comment by alRex-U** [comment]
Thank you for reporting.
Now I am working to fix these incompatibilities problem. Please wait.
