### ISSUE TITLE
[Enhancement] If there's a Fabric port planned...

### ISSUE THREAD

**Issue by bassistracer** [alRex-U/ParCool#99]
...think you may be able to use the same animation library [Better Combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus) uses? Not quite sure what it uses, but it would help prevent crashes in the future.

**Comment by alRex-U** [comment]
Now I have no plan to port to fabric. However if I did it, I would use spongepowered mixin directly. Thank-you for suggesting.
